import type { PlayerPosition } from "../../core/entities/PlayerPosition";
import type { ScalarValueInput } from "../../core/types/DomainScalars";

export function create_default_player_positions_for_organization(
  organization_id: ScalarValueInput<PlayerPosition["organization_id"]>,
): import("$lib/core/types/DomainScalars").ScalarInput<PlayerPosition>[] {
  const now = new Date().toISOString();
  const BASE = {
    sport_type: "Field Hockey",
    is_available: true,
    status: "active" as const,
    organization_id,
    created_at: now,
    updated_at: now,
  };

  return [
    {
      ...BASE,
      id: `player_position_hockey_gk_${organization_id}`,
      name: "Goalkeeper",
      code: "GK",
      category: "goalkeeper" as const,
      description: "Protects the goal and prevents scoring",
      display_order: 1,
    },
    {
      ...BASE,
      id: `player_position_hockey_sw_${organization_id}`,
      name: "Sweeper",
      code: "SW",
      category: "defender" as const,
      description: "Last line of defense in front of goalkeeper",
      display_order: 2,
    },
    {
      ...BASE,
      id: `player_position_hockey_cb_${organization_id}`,
      name: "Center Back",
      code: "CB",
      category: "defender" as const,
      description: "Central defensive position",
      display_order: 3,
    },
    {
      ...BASE,
      id: `player_position_hockey_lb_${organization_id}`,
      name: "Left Back",
      code: "LB",
      category: "defender" as const,
      description: "Left side defensive position",
      display_order: 4,
    },
    {
      ...BASE,
      id: `player_position_hockey_rb_${organization_id}`,
      name: "Right Back",
      code: "RB",
      category: "defender" as const,
      description: "Right side defensive position",
      display_order: 5,
    },
    {
      ...BASE,
      id: `player_position_hockey_cdm_${organization_id}`,
      name: "Defensive Midfielder",
      code: "CDM",
      category: "midfielder" as const,
      description: "Central defensive midfield position",
      display_order: 6,
    },
    {
      ...BASE,
      id: `player_position_hockey_cm_${organization_id}`,
      name: "Center Midfielder",
      code: "CM",
      category: "midfielder" as const,
      description: "Central midfield position",
      display_order: 7,
    },
    {
      ...BASE,
      id: `player_position_hockey_lm_${organization_id}`,
      name: "Left Midfielder",
      code: "LM",
      category: "midfielder" as const,
      description: "Left side midfield position",
      display_order: 8,
    },
    {
      ...BASE,
      id: `player_position_hockey_rm_${organization_id}`,
      name: "Right Midfielder",
      code: "RM",
      category: "midfielder" as const,
      description: "Right side midfield position",
      display_order: 9,
    },
    {
      ...BASE,
      id: `player_position_hockey_lw_${organization_id}`,
      name: "Left Wing",
      code: "LW",
      category: "forward" as const,
      description: "Left attacking wing position",
      display_order: 10,
    },
    {
      ...BASE,
      id: `player_position_hockey_rw_${organization_id}`,
      name: "Right Wing",
      code: "RW",
      category: "forward" as const,
      description: "Right attacking wing position",
      display_order: 11,
    },
    {
      ...BASE,
      id: `player_position_hockey_cf_${organization_id}`,
      name: "Center Forward",
      code: "CF",
      category: "forward" as const,
      description: "Central attacking forward position",
      display_order: 12,
    },
    {
      ...BASE,
      id: `player_position_hockey_st_${organization_id}`,
      name: "Striker",
      code: "ST",
      category: "forward" as const,
      description: "Main goal scoring position",
      display_order: 13,
    },
    {
      ...BASE,
      id: `player_position_hockey_if_${organization_id}`,
      name: "Inside Forward",
      code: "IF",
      category: "forward" as const,
      description: "Inside attacking forward supporting strikers",
      display_order: 14,
    },
  ] as PlayerPosition[];
}
