import { defineTable } from "convex/server";
import { v } from "convex/values";

import {
  assigned_official_validator,
  card_type_validator,
  foul_category_validator,
  game_event_validator,
  jersey_color_assignment_validator,
  official_requirement_validator,
  overtime_rule_validator,
  scoring_rule_validator,
  sport_game_period_validator,
  substitution_rule_validator,
  sync_metadata_fields,
  timestamp_fields,
} from "./schema_validators";

export const schema_match_tables = {
  players: defineTable({
    ...sync_metadata_fields,
    first_name: v.string(),
    last_name: v.string(),
    gender_id: v.optional(v.string()),
    organization_id: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    date_of_birth: v.optional(v.string()),
    position_id: v.optional(v.string()),
    nationality: v.optional(v.string()),
    height_cm: v.optional(v.union(v.number(), v.null())),
    weight_kg: v.optional(v.union(v.number(), v.null())),
    profile_image_url: v.optional(v.string()),
    emergency_contact_name: v.optional(v.string()),
    emergency_contact_phone: v.optional(v.string()),
    medical_notes: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_email", ["email"]),
  officials: defineTable({
    ...sync_metadata_fields,
    first_name: v.string(),
    last_name: v.string(),
    gender_id: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    date_of_birth: v.optional(v.string()),
    organization_id: v.optional(v.string()),
    years_of_experience: v.optional(v.number()),
    nationality: v.optional(v.string()),
    profile_image_url: v.optional(v.string()),
    emergency_contact_name: v.optional(v.string()),
    emergency_contact_phone: v.optional(v.string()),
    notes: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_email", ["email"]),
  fixtures: defineTable({
    ...sync_metadata_fields,
    organization_id: v.optional(v.string()),
    competition_id: v.optional(v.string()),
    round_number: v.optional(v.union(v.number(), v.null())),
    round_name: v.optional(v.string()),
    home_team_id: v.optional(v.string()),
    away_team_id: v.optional(v.string()),
    venue_id: v.optional(v.string()),
    venue: v.optional(v.string()),
    scheduled_date: v.optional(v.string()),
    scheduled_time: v.optional(v.string()),
    actual_start_time: v.optional(v.string()),
    actual_end_time: v.optional(v.string()),
    home_score: v.optional(v.union(v.number(), v.null())),
    away_score: v.optional(v.union(v.number(), v.null())),
    home_team_score: v.optional(v.union(v.number(), v.null())),
    away_team_score: v.optional(v.union(v.number(), v.null())),
    assigned_officials: v.optional(v.array(assigned_official_validator)),
    game_events: v.optional(v.array(game_event_validator)),
    current_period: v.optional(v.string()),
    current_minute: v.optional(v.union(v.number(), v.null())),
    match_day: v.optional(v.union(v.number(), v.null())),
    notes: v.optional(v.string()),
    status: v.optional(v.string()),
    round: v.optional(v.string()),
    home_team_name: v.optional(v.string()),
    away_team_name: v.optional(v.string()),
    home_team_jersey: v.optional(jersey_color_assignment_validator),
    away_team_jersey: v.optional(jersey_color_assignment_validator),
    officials_jersey: v.optional(jersey_color_assignment_validator),
    stage_id: v.optional(v.string()),
    manual_importance_override: v.optional(v.union(v.number(), v.null())),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  competition_stages: defineTable({
    ...sync_metadata_fields,
    competition_id: v.string(),
    name: v.string(),
    stage_type: v.string(),
    stage_order: v.number(),
    status: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_competition", ["competition_id"]),
  sports: defineTable({
    ...sync_metadata_fields,
    name: v.string(),
    code: v.optional(v.string()),
    description: v.optional(v.string()),
    icon: v.optional(v.string()),
    icon_url: v.optional(v.string()),
    standard_game_duration_minutes: v.optional(v.number()),
    periods: v.optional(v.array(sport_game_period_validator)),
    card_types: v.optional(v.array(card_type_validator)),
    foul_categories: v.optional(v.array(foul_category_validator)),
    official_requirements: v.optional(v.array(official_requirement_validator)),
    overtime_rules: v.optional(overtime_rule_validator),
    scoring_rules: v.optional(v.array(scoring_rule_validator)),
    substitution_rules: v.optional(substitution_rule_validator),
    max_players_on_field: v.optional(v.number()),
    min_players_on_field: v.optional(v.number()),
    max_squad_size: v.optional(v.number()),
    min_players_per_fixture: v.optional(v.number()),
    max_players_per_fixture: v.optional(v.number()),
    max_players_per_team: v.optional(v.number()),
    min_players_per_team: v.optional(v.number()),
    game_duration_minutes: v.optional(v.number()),
    period_duration_minutes: v.optional(v.number()),
    additional_rules: v.optional(
      v.record(v.string(), v.union(v.string(), v.number(), v.boolean())),
    ),
    rule_overrides: v.optional(
      v.record(v.string(), v.union(v.string(), v.number(), v.boolean())),
    ),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
};
