import { defineTable } from "convex/server";
import { v } from "convex/values";

import { sync_metadata_fields, timestamp_fields } from "./schema_validators";

export const schema_support_tables = {
  activity_categories: defineTable({
    ...sync_metadata_fields,
    name: v.string(),
    description: v.optional(v.string()),
    organization_id: v.optional(v.string()),
    category_type: v.optional(v.string()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    is_system_generated: v.optional(v.boolean()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  audit_logs: defineTable({
    ...sync_metadata_fields,
    action: v.string(),
    entity_type: v.string(),
    entity_id: v.string(),
    entity_display_name: v.optional(v.string()),
    organization_id: v.optional(v.string()),
    user_id: v.optional(v.string()),
    user_email: v.optional(v.string()),
    user_display_name: v.optional(v.string()),
    correlation_id: v.optional(v.string()),
    changes: v.optional(
      v.array(
        v.object({
          field_name: v.string(),
          old_value: v.string(),
          new_value: v.string(),
        }),
      ),
    ),
    timestamp: v.optional(v.string()),
    old_values: v.optional(v.string()),
    new_values: v.optional(v.string()),
    ip_address: v.optional(v.string()),
    user_agent: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_entity", ["entity_type", "entity_id"])
    .index("by_timestamp", ["timestamp"])
    .index("by_organization", ["organization_id"]),
  system_users: defineTable({
    ...sync_metadata_fields,
    email: v.string(),
    first_name: v.optional(v.string()),
    last_name: v.optional(v.string()),
    name: v.optional(v.string()),
    role: v.string(),
    organization_id: v.optional(v.string()),
    team_id: v.optional(v.string()),
    player_id: v.optional(v.string()),
    official_id: v.optional(v.string()),
    avatar_url: v.optional(v.string()),
    profile_picture_base64: v.optional(v.string()),
    status: v.optional(v.string()),
    last_login_at: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_email", ["email"]),
  identification_types: defineTable({
    ...sync_metadata_fields,
    organization_id: v.string(),
    name: v.string(),
    identifier_field_label: v.optional(v.string()),
    country: v.optional(v.string()),
    description: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  identifications: defineTable({
    ...sync_metadata_fields,
    entity_type: v.optional(v.string()),
    entity_id: v.optional(v.string()),
    holder_type: v.optional(v.string()),
    holder_id: v.optional(v.string()),
    identification_type_id: v.optional(v.string()),
    identification_number: v.optional(v.string()),
    identifier_value: v.optional(v.string()),
    issue_date: v.optional(v.string()),
    expiry_date: v.optional(v.string()),
    document_url: v.optional(v.string()),
    document_image_url: v.optional(v.string()),
    notes: v.optional(v.string()),
    is_verified: v.optional(v.boolean()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  qualifications: defineTable({
    ...sync_metadata_fields,
    holder_type: v.optional(v.string()),
    holder_id: v.optional(v.string()),
    entity_type: v.optional(v.string()),
    entity_id: v.optional(v.string()),
    name: v.optional(v.string()),
    certification_name: v.optional(v.string()),
    certification_level: v.optional(v.string()),
    certification_number: v.optional(v.string()),
    issuing_authority: v.optional(v.string()),
    issuing_body: v.optional(v.string()),
    issue_date: v.optional(v.string()),
    expiry_date: v.optional(v.string()),
    specializations: v.optional(v.array(v.string())),
    notes: v.optional(v.string()),
    document_url: v.optional(v.string()),
    is_verified: v.optional(v.boolean()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  game_event_types: defineTable({
    ...sync_metadata_fields,
    organization_id: v.string(),
    name: v.string(),
    code: v.optional(v.string()),
    sport_id: v.optional(v.union(v.string(), v.null())),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    icon: v.optional(v.string()),
    color: v.optional(v.string()),
    affects_score: v.optional(v.boolean()),
    requires_player: v.optional(v.boolean()),
    display_order: v.optional(v.number()),
    score_value: v.optional(v.number()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  genders: defineTable({
    ...sync_metadata_fields,
    organization_id: v.string(),
    name: v.string(),
    description: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
};
