import { defineTable } from "convex/server";
import { v } from "convex/values";

import { sync_metadata_fields, timestamp_fields } from "./schema_validators";

export const schema_staff_and_location_tables = {
  team_staff: defineTable({
    ...sync_metadata_fields,
    organization_id: v.optional(v.string()),
    team_id: v.string(),
    role_id: v.optional(v.string()),
    first_name: v.string(),
    last_name: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    photo_url: v.optional(v.string()),
    profile_image_url: v.optional(v.string()),
    date_of_birth: v.optional(v.string()),
    nationality: v.optional(v.string()),
    emergency_contact_name: v.optional(v.string()),
    emergency_contact_phone: v.optional(v.string()),
    employment_start_date: v.optional(v.string()),
    employment_end_date: v.optional(v.string()),
    notes: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_team", ["team_id"]),
  team_staff_roles: defineTable({
    ...sync_metadata_fields,
    organization_id: v.string(),
    name: v.string(),
    code: v.optional(v.string()),
    sport_id: v.optional(v.string()),
    description: v.optional(v.string()),
    category: v.optional(v.string()),
    is_primary_contact: v.optional(v.boolean()),
    display_order: v.optional(v.number()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  game_official_roles: defineTable({
    ...sync_metadata_fields,
    organization_id: v.string(),
    name: v.string(),
    code: v.optional(v.string()),
    sport_id: v.optional(v.string()),
    description: v.optional(v.string()),
    is_required: v.optional(v.boolean()),
    is_on_field: v.optional(v.boolean()),
    is_head_official: v.optional(v.boolean()),
    sort_order: v.optional(v.number()),
    display_order: v.optional(v.number()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  venues: defineTable({
    ...sync_metadata_fields,
    organization_id: v.optional(v.string()),
    name: v.string(),
    short_name: v.optional(v.string()),
    address: v.optional(v.string()),
    city: v.optional(v.string()),
    country: v.optional(v.string()),
    capacity: v.optional(v.number()),
    surface_type: v.optional(v.string()),
    has_lighting: v.optional(v.boolean()),
    has_parking: v.optional(v.boolean()),
    contact_email: v.optional(v.string()),
    contact_phone: v.optional(v.string()),
    website: v.optional(v.string()),
    image_url: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    photo_url: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  jersey_colors: defineTable({
    ...sync_metadata_fields,
    holder_type: v.optional(v.string()),
    holder_id: v.optional(v.string()),
    nickname: v.optional(v.string()),
    main_color: v.optional(v.string()),
    secondary_color: v.optional(v.string()),
    tertiary_color: v.optional(v.string()),
    name: v.optional(v.string()),
    hex_code: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  player_positions: defineTable({
    ...sync_metadata_fields,
    organization_id: v.string(),
    name: v.string(),
    code: v.optional(v.string()),
    category: v.optional(v.string()),
    abbreviation: v.optional(v.string()),
    sport_id: v.optional(v.string()),
    sport_type: v.optional(v.string()),
    description: v.optional(v.string()),
    display_order: v.optional(v.number()),
    is_available: v.optional(v.boolean()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
};
