import { defineTable } from "convex/server";
import { v } from "convex/values";

import {
  card_type_validator,
  foul_category_validator,
  official_requirement_validator,
  overtime_rule_validator,
  scoring_rule_validator,
  sport_game_period_validator,
  substitution_rule_validator,
  sync_metadata_fields,
  timestamp_fields,
} from "./schema_validators";

export const schema_competition_tables = {
  organizations: defineTable({
    ...sync_metadata_fields,
    name: v.string(),
    description: v.optional(v.string()),
    sport_id: v.string(),
    logo_url: v.optional(v.string()),
    website: v.optional(v.string()),
    contact_email: v.optional(v.string()),
    contact_phone: v.optional(v.string()),
    address: v.optional(v.string()),
    founded_date: v.optional(v.string()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  competitions: defineTable({
    ...sync_metadata_fields,
    name: v.string(),
    description: v.optional(v.string()),
    organization_id: v.optional(v.string()),
    competition_format_id: v.optional(v.string()),
    format_id: v.optional(v.string()),
    team_ids: v.optional(v.array(v.string())),
    allow_auto_squad_submission: v.optional(v.boolean()),
    squad_generation_strategy: v.optional(v.string()),
    allow_auto_fixture_details_setup: v.optional(v.boolean()),
    lineup_submission_deadline_hours: v.optional(v.number()),
    season: v.optional(v.string()),
    start_date: v.optional(v.string()),
    end_date: v.optional(v.string()),
    registration_deadline: v.optional(v.string()),
    max_teams: v.optional(v.number()),
    entry_fee: v.optional(v.number()),
    prize_pool: v.optional(v.number()),
    location: v.optional(v.string()),
    rule_overrides: v.optional(
      v.object({
        game_duration_minutes: v.optional(v.number()),
        periods: v.optional(v.array(sport_game_period_validator)),
        additional_card_types: v.optional(v.array(card_type_validator)),
        additional_foul_categories: v.optional(
          v.array(foul_category_validator),
        ),
        official_requirements: v.optional(
          v.array(official_requirement_validator),
        ),
        overtime_rules: v.optional(overtime_rule_validator),
        scoring_rules: v.optional(v.array(scoring_rule_validator)),
        substitution_rules: v.optional(substitution_rule_validator),
        max_players_on_field: v.optional(v.number()),
        min_players_on_field: v.optional(v.number()),
        max_squad_size: v.optional(v.number()),
        custom_rules: v.optional(v.record(v.string(), v.string())),
        points_config_override: v.optional(
          v.object({
            points_for_win: v.optional(v.number()),
            points_for_draw: v.optional(v.number()),
            points_for_loss: v.optional(v.number()),
          }),
        ),
        tie_breakers_override: v.optional(v.array(v.string())),
      }),
    ),
    status: v.optional(v.string()),
    logo_url: v.optional(v.string()),
    ...timestamp_fields,
  }).index("by_local_id", ["local_id"]),
  teams: defineTable({
    ...sync_metadata_fields,
    name: v.string(),
    short_name: v.optional(v.string()),
    description: v.optional(v.string()),
    organization_id: v.string(),
    gender_id: v.optional(v.string()),
    captain_player_id: v.optional(v.string()),
    vice_captain_player_id: v.optional(v.string()),
    max_squad_size: v.optional(v.number()),
    logo_url: v.optional(v.string()),
    primary_color: v.optional(v.string()),
    secondary_color: v.optional(v.string()),
    jersey_colors: v.optional(v.string()),
    home_venue_id: v.optional(v.string()),
    website: v.optional(v.string()),
    founded_year: v.optional(v.number()),
    status: v.optional(v.string()),
    ...timestamp_fields,
  })
    .index("by_local_id", ["local_id"])
    .index("by_organization", ["organization_id"]),
};
