export const SIDEBAR_MENU_SEED_ITEMS = [
  ["super_admin", "Home", 1, "Dashboard", "/", "DASHBOARD", 1],
  ["super_admin", "Home", 1, "Calendar", "/calendar", "CALENDAR", 2],
  ["super_admin", "Home", 1, "Live Games", "/live-games", "LIVE_GAMES", 3],
  [
    "super_admin",
    "Home",
    1,
    "Competition Results",
    "/competition-results",
    "RESULTS",
    4,
  ],
  ["super_admin", "Home", 1, "Help", "/help", "HELP", 5],
  [
    "super_admin",
    "Organization",
    2,
    "Organizations",
    "/organizations",
    "ORG",
    1,
  ],
  ["super_admin", "Organization", 2, "Sports", "/sports", "SPORTS", 2],
  ["super_admin", "Organization", 2, "Venues", "/venues", "VENUES", 3],
  [
    "super_admin",
    "Competitions",
    3,
    "Competitions",
    "/competitions",
    "COMPETITIONS",
    1,
  ],
  [
    "super_admin",
    "Competitions",
    3,
    "Competition Formats",
    "/competition-formats",
    "FORMATS",
    2,
  ],
  ["super_admin", "Teams", 4, "Teams", "/teams", "TEAMS", 1],
  ["super_admin", "Teams", 4, "Team Staff", "/team-staff", "STAFF", 3],
  ["super_admin", "Teams", 4, "Staff Roles", "/staff-roles", "TAG", 4],
  ["super_admin", "Players", 5, "Players", "/players", "PLAYERS", 1],
  [
    "super_admin",
    "Players",
    5,
    "Player Team Memberships",
    "/player-team-memberships",
    "MEMBERSHIP",
    3,
  ],
  [
    "super_admin",
    "Players",
    5,
    "Player Transfers",
    "/player-transfers",
    "TRANSFER",
    4,
  ],
  [
    "super_admin",
    "Players",
    5,
    "Player Positions",
    "/player-positions",
    "POSITIONS",
    5,
  ],
  ["super_admin", "Officials", 6, "Officials", "/officials", "OFFICIALS", 1],
  [
    "super_admin",
    "Officials",
    6,
    "Official Roles",
    "/official-roles",
    "TAG",
    2,
  ],
  [
    "super_admin",
    "Fixtures & Games",
    7,
    "Fixtures",
    "/fixtures",
    "CALENDAR",
    1,
  ],
  [
    "super_admin",
    "Fixtures & Games",
    7,
    "Team Lineups",
    "/fixture-lineups",
    "LINEUPS",
    2,
  ],
  [
    "super_admin",
    "Fixtures & Games",
    7,
    "Fixture Details Setup",
    "/fixture-details-setup",
    "OFFICIALS",
    3,
  ],
  [
    "super_admin",
    "Fixtures & Games",
    7,
    "Game Event Types",
    "/event-types",
    "EVENTS",
    4,
  ],
  [
    "super_admin",
    "Administration",
    8,
    "System Users",
    "/system-users",
    "USERS",
    1,
  ],
  [
    "super_admin",
    "Administration",
    8,
    "ID Types",
    "/identification-types",
    "ID",
    2,
  ],
  ["super_admin", "Administration", 8, "Genders", "/genders", "GENDERS", 3],
  [
    "super_admin",
    "Administration",
    8,
    "Audit Trail",
    "/audit-logs",
    "AUDIT",
    4,
  ],
  ["org_admin", "Home", 1, "Dashboard", "/", "DASHBOARD", 1],
  ["org_admin", "Home", 1, "Calendar", "/calendar", "CALENDAR", 2],
  ["org_admin", "Home", 1, "Live Games", "/live-games", "LIVE_GAMES", 3],
  [
    "org_admin",
    "Home",
    1,
    "Competition Results",
    "/competition-results",
    "RESULTS",
    4,
  ],
  ["org_admin", "Organization", 2, "Venues", "/venues", "VENUES", 1],
  [
    "org_admin",
    "Competitions",
    3,
    "Competitions",
    "/competitions",
    "COMPETITIONS",
    1,
  ],
  [
    "org_admin",
    "Competitions",
    3,
    "Competition Formats",
    "/competition-formats",
    "FORMATS",
    2,
  ],
  ["org_admin", "Teams", 4, "Teams", "/teams", "TEAMS", 1],
  ["org_admin", "Teams", 4, "Team Staff", "/team-staff", "STAFF", 3],
  ["org_admin", "Teams", 4, "Staff Roles", "/staff-roles", "TAG", 4],
  ["org_admin", "Players", 5, "Players", "/players", "PLAYERS", 1],
  [
    "org_admin",
    "Players",
    5,
    "Player Team Memberships",
    "/player-team-memberships",
    "MEMBERSHIP",
    3,
  ],
  [
    "org_admin",
    "Players",
    5,
    "Player Transfers",
    "/player-transfers",
    "TRANSFER",
    4,
  ],
  [
    "org_admin",
    "Players",
    5,
    "Player Positions",
    "/player-positions",
    "POSITIONS",
    5,
  ],
  ["org_admin", "Officials", 6, "Officials", "/officials", "OFFICIALS", 1],
  ["org_admin", "Officials", 6, "Official Roles", "/official-roles", "TAG", 2],
  ["org_admin", "Fixtures & Games", 7, "Fixtures", "/fixtures", "CALENDAR", 1],
  [
    "org_admin",
    "Fixtures & Games",
    7,
    "Team Lineups",
    "/fixture-lineups",
    "LINEUPS",
    2,
  ],
  [
    "org_admin",
    "Fixtures & Games",
    7,
    "Fixture Details Setup",
    "/fixture-details-setup",
    "OFFICIALS",
    3,
  ],
  [
    "org_admin",
    "Fixtures & Games",
    7,
    "Game Event Types",
    "/event-types",
    "EVENTS",
    4,
  ],
  ["org_admin", "Administration", 8, "Settings", "/settings", "SETTINGS", 1],
  [
    "org_admin",
    "Administration",
    8,
    "ID Types",
    "/identification-types",
    "ID",
    2,
  ],
  ["org_admin", "Administration", 8, "Audit Trail", "/audit-logs", "AUDIT", 3],
  ["officials_manager", "Home", 1, "Dashboard", "/", "DASHBOARD", 1],
  ["officials_manager", "Home", 1, "Calendar", "/calendar", "CALENDAR", 2],
  [
    "officials_manager",
    "Home",
    1,
    "Live Games",
    "/live-games",
    "LIVE_GAMES",
    3,
  ],
  [
    "officials_manager",
    "Home",
    1,
    "Competition Results",
    "/competition-results",
    "RESULTS",
    4,
  ],
  [
    "officials_manager",
    "Officials",
    2,
    "Officials",
    "/officials",
    "OFFICIALS",
    1,
  ],
  [
    "officials_manager",
    "Officials",
    2,
    "Official Roles",
    "/official-roles",
    "TAG",
    2,
  ],
  [
    "officials_manager",
    "Fixtures & Games",
    3,
    "Fixtures",
    "/fixtures",
    "CALENDAR",
    1,
  ],
  [
    "officials_manager",
    "Fixtures & Games",
    3,
    "Fixture Details Setup",
    "/fixture-details-setup",
    "OFFICIALS",
    2,
  ],
  ["team_manager", "Home", 1, "Dashboard", "/", "DASHBOARD", 1],
  ["team_manager", "Home", 1, "Calendar", "/calendar", "CALENDAR", 2],
  [
    "team_manager",
    "Home",
    1,
    "Competition Results",
    "/competition-results",
    "RESULTS",
    3,
  ],
  ["team_manager", "My Team", 2, "My Team", "/teams", "TEAMS", 1],
  ["team_manager", "My Team", 2, "My Team Staff", "/team-staff", "STAFF", 3],
  ["team_manager", "My Team", 2, "My Players", "/players", "USERS", 4],
  [
    "team_manager",
    "Fixtures & Games",
    3,
    "Fixtures",
    "/fixtures",
    "CALENDAR",
    1,
  ],
  [
    "team_manager",
    "Fixtures & Games",
    3,
    "Team Lineups",
    "/fixture-lineups",
    "LINEUPS",
    2,
  ],
  [
    "team_manager",
    "Officials",
    4,
    "Officials Performance",
    "/official-performance",
    "OFFICIALS",
    1,
  ],
  ["official", "Home", 1, "Dashboard", "/", "DASHBOARD", 1],
  ["official", "Home", 1, "Calendar", "/calendar", "CALENDAR", 2],
  ["official", "Home", 1, "Live Games", "/live-games", "LIVE_GAMES", 3],
  [
    "official",
    "Home",
    1,
    "Competition Results",
    "/competition-results",
    "RESULTS",
    4,
  ],
  ["official", "My Info", 2, "My Official Profile", "/officials", "PROFILE", 1],
  ["player", "Home", 1, "Dashboard", "/", "DASHBOARD", 1],
  ["player", "Home", 1, "Calendar", "/calendar", "CALENDAR", 2],
  [
    "player",
    "Home",
    1,
    "Competition Results",
    "/competition-results",
    "RESULTS",
    3,
  ],
  ["player", "My Info", 2, "My Player Record", "/players", "PLAYERS", 1],
  [
    "player",
    "My Info",
    2,
    "My Team Memberships",
    "/player-team-memberships",
    "TEAMS",
    3,
  ],
  ["player", "Fixtures", 3, "My Fixtures", "/fixtures", "CALENDAR", 1],
] as const;
