import {
  create_help_guide_step,
  type HelpGuideStep,
} from "./helpGuideStepTypes";

export const HELP_GUIDE_LIVE_STEPS: HelpGuideStep[] = [
  create_help_guide_step(
    17,
    "Assign Officials to Fixtures",
    "Appoint referees and officials for each scheduled match.",
    "/fixtures",
    [
      "Go to the Fixture detail page",
      "Find the Officials assignment section",
      "Add Main Referee for the match",
      "Add Assistant Referees",
      "Add Fourth Official if required",
      "Officials receive their assignments",
      "Ensures proper match coverage",
    ],
  ),
  create_help_guide_step(
    18,
    "Prepare Match Lineups",
    "Set starting lineups and substitutes for upcoming fixtures.",
    "/fixture-lineups/create",
    [
      "Navigate to Fixture Lineups",
      "Select the fixture to prepare",
      "Choose starting XI (or appropriate number)",
      "Assign jersey numbers and positions",
      "Add substitute players",
      "Include team staff on the bench",
      "Lineups can be modified until match starts",
    ],
  ),
  create_help_guide_step(
    19,
    "Start a Live Game",
    "Begin live scoring and match management for a fixture.",
    "/live-games",
    [
      "Go to Live Games from the sidebar",
      "Or click 'Manage' on a fixture from Fixtures list",
      "Click 'Start Game' when ready",
      "The match clock begins automatically",
      "Current period is tracked (1st half, 2nd half, etc.)",
      "Both teams' lineups are displayed",
      "Score updates appear in real-time",
    ],
  ),
  create_help_guide_step(
    20,
    "Record Match Events",
    "Log goals, cards, substitutions, and other match events as they happen.",
    "/live-games",
    [
      "During a live game, use the event controls",
      "Record goals with scorer and time",
      "Log yellow and red cards",
      "Record substitutions (player in/out)",
      "Add assists if applicable",
      "Track injuries or stoppages",
      "All events are timestamped automatically",
    ],
  ),
  create_help_guide_step(
    21,
    "Manage Game Periods",
    "Control half-time, extra time, and period transitions during matches.",
    "/live-games",
    [
      "Use 'End Period' to conclude current period",
      "Start next period when teams are ready",
      "Half-time break is tracked automatically",
      "Add extra time if regulations require",
      "Penalty shootouts can be recorded",
      "Match duration is calculated precisely",
      "Period-by-period stats are maintained",
    ],
  ),
  create_help_guide_step(
    22,
    "Complete the Game",
    "Finalize the match and confirm the final result.",
    "/live-games",
    [
      "When all periods are complete, click 'End Game'",
      "Final score is locked and recorded",
      "Match status changes to 'Completed'",
      "Results are automatically added to standings",
      "Player statistics are updated",
      "Match report becomes available",
      "Competition table recalculates immediately",
    ],
  ),
  create_help_guide_step(
    23,
    "View Competition Results",
    "Check standings, results, and statistics for your competition.",
    "/competition-results",
    [
      "Navigate to Competition Results",
      "Select the competition to view",
      "See the current standings table",
      "Points, wins, draws, losses displayed",
      "Goal difference and goals scored/conceded",
      "Click teams to see their match history",
      "Track who's leading, who needs improvement",
    ],
  ),
];
