import {
  create_help_guide_step,
  type HelpGuideStep,
} from "./helpGuideStepTypes";

export const HELP_GUIDE_SETUP_STEPS: HelpGuideStep[] = [
  create_help_guide_step(
    1,
    "Create a Sport",
    "Define the sport your organization will manage. This establishes the rules, scoring system, and game structure.",
    "/sports/create",
    [
      "Navigate to Sports from the sidebar menu",
      "Click 'Add Sport' to create a new sport entry",
      "Enter the sport name (e.g., Football, Basketball, Rugby)",
      "Configure game periods (halves, quarters, sets, etc.)",
      "Set period duration and any break times",
      "Define scoring types (goals, points, tries, etc.)",
      "Save to establish your sport foundation",
    ],
  ),
  create_help_guide_step(
    2,
    "Set Up Your Organization",
    "Create your sports organization that will govern competitions, teams, and officials.",
    "/organizations",
    [
      "Go to Organizations from the sidebar",
      "Click 'Add Organization' to create new",
      "Enter organization name and details",
      "Add contact information (email, address)",
      "Upload your organization logo in Settings",
      "Configure branding colors to match your identity",
      "Add social media links for public visibility",
    ],
  ),
  create_help_guide_step(
    3,
    "Create Teams",
    "Register the teams that will participate in your competitions.",
    "/teams",
    [
      "Navigate to Teams from the sidebar",
      "Click 'Add Team' to register a new team",
      "Enter team name and nickname",
      "Select the sport the team plays",
      "Associate the team with your organization",
      "Upload team logo for identification",
      "Note the home venue if applicable",
    ],
  ),
  create_help_guide_step(
    4,
    "Set Up Team Profiles & Jerseys",
    "Configure team visual identity including jersey colors for home and away matches.",
    "/team-profiles",
    [
      "Go to Team Profiles from the sidebar",
      "Select the team to configure",
      "Set primary jersey color (home matches)",
      "Set secondary jersey color (away matches)",
      "Define jersey patterns if applicable",
      "Upload team photos or crests",
      "This helps distinguish teams during live games",
    ],
  ),
  create_help_guide_step(
    5,
    "Register Players",
    "Add players to your system who can then be assigned to teams.",
    "/players",
    [
      "Navigate to Players from the sidebar",
      "Click 'Add Player' to register new players",
      "Enter player personal details (name, date of birth)",
      "Add identification information if required",
      "Upload player photo for profiles",
      "Players can later be assigned to multiple teams",
      "Track player statistics across competitions",
    ],
  ),
  create_help_guide_step(
    6,
    "Assign Players to Teams",
    "Create team rosters by assigning registered players to teams.",
    "/player-team-memberships",
    [
      "Go to Player Team Memberships",
      "Click 'Add Membership' to assign a player",
      "Select the player from the registry",
      "Choose the team they will play for",
      "Set their jersey number for that team",
      "Assign their playing position",
      "Set membership dates (season start/end)",
    ],
  ),
  create_help_guide_step(
    7,
    "Configure Player Positions",
    "Define the positions players can occupy based on your sport.",
    "/player-positions",
    [
      "Navigate to Player Positions",
      "Create positions specific to your sport",
      "For football: Goalkeeper, Defender, Midfielder, Forward",
      "For basketball: Point Guard, Center, etc.",
      "Positions are used in lineup management",
      "Helps with tactical planning and statistics",
      "Can track position-specific performance metrics",
    ],
  ),
  create_help_guide_step(
    8,
    "Register Officials",
    "Add referees, umpires, and other match officials to your system.",
    "/officials",
    [
      "Go to Officials from the sidebar",
      "Click 'Add Official' to register",
      "Enter official personal details",
      "Assign official roles (referee, assistant, etc.)",
      "Set certification/qualification level",
      "Associate with your organization",
      "Officials can be assigned to fixtures later",
    ],
  ),
];
