import {
  create_help_guide_step,
  type HelpGuideStep,
} from "./helpGuideStepTypes";

export const HELP_GUIDE_COMPETITION_STEPS: HelpGuideStep[] = [
  create_help_guide_step(
    9,
    "Configure Official Roles",
    "Define the types of officiating roles available in your sport.",
    "/official-roles",
    [
      "Navigate to Official Roles",
      "Create roles like Main Referee, Assistant Referee",
      "Add Fourth Official, Video Referee if applicable",
      "Define responsibilities for each role",
      "Roles help organize match day assignments",
      "Ensures proper coverage for all matches",
      "Can track official performance by role",
    ],
  ),
  create_help_guide_step(
    10,
    "Register Staff Members",
    "Add coaches, managers, physiotherapists, and other team staff.",
    "/team-staff",
    [
      "Go to Team Staff from the sidebar",
      "Click 'Add Staff' to register",
      "Enter staff member details",
      "Assign to specific teams",
      "Define their staff role",
      "Staff appear on team sheets",
      "Can track staff certifications and licenses",
    ],
  ),
  create_help_guide_step(
    11,
    "Configure Staff Roles",
    "Define the types of staff positions available for teams.",
    "/staff-roles",
    [
      "Navigate to Staff Roles",
      "Create roles like Head Coach, Assistant Coach",
      "Add Team Manager, Physiotherapist, etc.",
      "Roles help organize team management",
      "Defines who can perform what actions",
      "Important for access control if implemented",
      "Shows proper hierarchy on team sheets",
    ],
  ),
  create_help_guide_step(
    12,
    "Set Up Venues",
    "Register stadiums, pitches, and courts where matches will be played.",
    "/venues/create",
    [
      "Go to Venues from the sidebar",
      "Click 'Add Venue' to create new",
      "Enter venue name and location",
      "Add address details for directions",
      "Set venue capacity if relevant",
      "Upload venue photos",
      "Venues are assigned to fixtures",
    ],
  ),
  create_help_guide_step(
    13,
    "Configure Competition Formats",
    "Define how competitions will be structured (league, knockout, groups).",
    "/competition-formats",
    [
      "Navigate to Competition Formats",
      "Create formats like Round Robin, Knockout",
      "Add Group Stage + Knockout combinations",
      "Define how standings are calculated",
      "Set tiebreaker rules",
      "Formats can be reused across competitions",
      "Determines how fixtures are generated",
    ],
  ),
  create_help_guide_step(
    14,
    "Create a Competition",
    "Set up a league, tournament, or championship for teams to compete in.",
    "/competitions/create",
    [
      "Go to Competitions from the sidebar",
      "Click 'Add Competition' to create new",
      "Enter competition name and description",
      "Select the sport type",
      "Choose competition format (league, knockout, etc.)",
      "Set start and end dates for the season",
      "Associate with your organization",
    ],
  ),
  create_help_guide_step(
    15,
    "Add Teams to Competition",
    "Register which teams will participate in your competition.",
    "/competitions",
    [
      "Go to the Competition detail page",
      "Find the Teams section",
      "Click 'Add Team' to include teams",
      "Select from your registered teams",
      "Set group assignments if applicable",
      "Confirm team registration status",
      "Teams appear in fixture scheduling",
    ],
  ),
  create_help_guide_step(
    16,
    "Create Fixtures",
    "Schedule matches between teams in your competition.",
    "/fixtures/create",
    [
      "Navigate to Fixtures from the sidebar",
      "Click 'Create Fixture' for new matches",
      "Select the competition",
      "Choose home team and away team",
      "Set match date and kick-off time",
      "Assign the venue for the match",
      "Set matchday/round number if applicable",
    ],
  ),
];
