export interface HelpGuideStep {
  step_number: number;
  title: string;
  description: string;
  link: string;
  details: string[];
}

function create_help_guide_step(
  step_number: number,
  title: string,
  description: string,
  link: string,
  details: string[],
): HelpGuideStep {
  return { step_number, title, description, link, details };
}

export const HELP_GUIDE_STEPS: HelpGuideStep[] = [
  create_help_guide_step(
    1,
    "Create a Sport",
    "Define the sport your organization will manage. This establishes the rules, scoring system, and game structure.",
    "/sports/create",
    [
      "Navigate to Sports from the sidebar menu",
      "Click 'Add Sport' to create a new sport entry",
      "Enter the sport name (e.g., Football, Basketball, Rugby)",
      "Configure game periods (halves, quarters, sets, etc.)",
      "Set period duration and any break times",
      "Define scoring types (goals, points, tries, etc.)",
      "Save to establish your sport foundation",
    ],
  ),
  create_help_guide_step(
    2,
    "Set Up Your Organization",
    "Create your sports organization that will govern competitions, teams, and officials.",
    "/organizations",
    [
      "Go to Organizations from the sidebar",
      "Click 'Add Organization' to create new",
      "Enter organization name and details",
      "Add contact information (email, address)",
      "Upload your organization logo in Settings",
      "Configure branding colors to match your identity",
      "Add social media links for public visibility",
    ],
  ),
  create_help_guide_step(
    3,
    "Create Teams",
    "Register the teams that will participate in your competitions.",
    "/teams",
    [
      "Navigate to Teams from the sidebar",
      "Click 'Add Team' to register a new team",
      "Enter team name and nickname",
      "Select the sport the team plays",
      "Associate the team with your organization",
      "Upload team logo for identification",
      "Note the home venue if applicable",
    ],
  ),
  create_help_guide_step(
    4,
    "Set Up Team Profiles & Jerseys",
    "Configure team visual identity including jersey colors for home and away matches.",
    "/team-profiles",
    [
      "Go to Team Profiles from the sidebar",
      "Select the team to configure",
      "Set primary jersey color (home matches)",
      "Set secondary jersey color (away matches)",
      "Define jersey patterns if applicable",
      "Upload team photos or crests",
      "This helps distinguish teams during live games",
    ],
  ),
  create_help_guide_step(
    5,
    "Register Players",
    "Add players to your system who can then be assigned to teams.",
    "/players",
    [
      "Navigate to Players from the sidebar",
      "Click 'Add Player' to register new players",
      "Enter player personal details (name, date of birth)",
      "Add identification information if required",
      "Upload player photo for profiles",
      "Players can later be assigned to multiple teams",
      "Track player statistics across competitions",
    ],
  ),
  create_help_guide_step(
    6,
    "Assign Players to Teams",
    "Create team rosters by assigning registered players to teams.",
    "/player-team-memberships",
    [
      "Go to Player Team Memberships",
      "Click 'Add Membership' to assign a player",
      "Select the player from the registry",
      "Choose the team they will play for",
      "Set their jersey number for that team",
      "Assign their playing position",
      "Set membership dates (season start/end)",
    ],
  ),
  create_help_guide_step(
    7,
    "Configure Player Positions",
    "Define the positions players can occupy based on your sport.",
    "/player-positions",
    [
      "Navigate to Player Positions",
      "Create positions specific to your sport",
      "For football: Goalkeeper, Defender, Midfielder, Forward",
      "For basketball: Point Guard, Center, etc.",
      "Positions are used in lineup management",
      "Helps with tactical planning and statistics",
      "Can track position-specific performance metrics",
    ],
  ),
  create_help_guide_step(
    8,
    "Register Officials",
    "Add referees, umpires, and other match officials to your system.",
    "/officials",
    [
      "Go to Officials from the sidebar",
      "Click 'Add Official' to register",
      "Enter official personal details",
      "Assign official roles (referee, assistant, etc.)",
      "Set certification/qualification level",
      "Associate with your organization",
      "Officials can be assigned to fixtures later",
    ],
  ),
  create_help_guide_step(
    9,
    "Configure Official Roles",
    "Define the types of officiating roles available in your sport.",
    "/official-roles",
    [
      "Navigate to Official Roles",
      "Create roles like Main Referee, Assistant Referee",
      "Add Fourth Official, Video Referee if applicable",
      "Define responsibilities for each role",
      "Roles help organize match day assignments",
      "Ensures proper coverage for all matches",
      "Can track official performance by role",
    ],
  ),
  create_help_guide_step(
    10,
    "Register Staff Members",
    "Add coaches, managers, physiotherapists, and other team staff.",
    "/team-staff",
    [
      "Go to Team Staff from the sidebar",
      "Click 'Add Staff' to register",
      "Enter staff member details",
      "Assign to specific teams",
      "Define their staff role",
      "Staff appear on team sheets",
      "Can track staff certifications and licenses",
    ],
  ),
  create_help_guide_step(
    11,
    "Configure Staff Roles",
    "Define the types of staff positions available for teams.",
    "/staff-roles",
    [
      "Navigate to Staff Roles",
      "Create roles like Head Coach, Assistant Coach",
      "Add Team Manager, Physiotherapist, etc.",
      "Roles help organize team management",
      "Defines who can perform what actions",
      "Important for access control if implemented",
      "Shows proper hierarchy on team sheets",
    ],
  ),
  create_help_guide_step(
    12,
    "Set Up Venues",
    "Register stadiums, pitches, and courts where matches will be played.",
    "/venues/create",
    [
      "Go to Venues from the sidebar",
      "Click 'Add Venue' to create new",
      "Enter venue name and location",
      "Add address details for directions",
      "Set venue capacity if relevant",
      "Upload venue photos",
      "Venues are assigned to fixtures",
    ],
  ),
  create_help_guide_step(
    13,
    "Configure Competition Formats",
    "Define how competitions will be structured (league, knockout, groups).",
    "/competition-formats",
    [
      "Navigate to Competition Formats",
      "Create formats like Round Robin, Knockout",
      "Add Group Stage + Knockout combinations",
      "Define how standings are calculated",
      "Set tiebreaker rules",
      "Formats can be reused across competitions",
      "Determines how fixtures are generated",
    ],
  ),
  create_help_guide_step(
    14,
    "Create a Competition",
    "Set up a league, tournament, or championship for teams to compete in.",
    "/competitions/create",
    [
      "Go to Competitions from the sidebar",
      "Click 'Add Competition' to create new",
      "Enter competition name and description",
      "Select the sport type",
      "Choose competition format (league, knockout, etc.)",
      "Set start and end dates for the season",
      "Associate with your organization",
    ],
  ),
  create_help_guide_step(
    15,
    "Add Teams to Competition",
    "Register which teams will participate in your competition.",
    "/competitions",
    [
      "Go to the Competition detail page",
      "Find the Teams section",
      "Click 'Add Team' to include teams",
      "Select from your registered teams",
      "Set group assignments if applicable",
      "Confirm team registration status",
      "Teams appear in fixture scheduling",
    ],
  ),
  create_help_guide_step(
    16,
    "Create Fixtures",
    "Schedule matches between teams in your competition.",
    "/fixtures/create",
    [
      "Navigate to Fixtures from the sidebar",
      "Click 'Create Fixture' for new matches",
      "Select the competition",
      "Choose home team and away team",
      "Set match date and kick-off time",
      "Assign the venue for the match",
      "Set matchday/round number if applicable",
    ],
  ),
  create_help_guide_step(
    17,
    "Assign Officials to Fixtures",
    "Appoint referees and officials for each scheduled match.",
    "/fixtures",
    [
      "Go to the Fixture detail page",
      "Find the Officials assignment section",
      "Add Main Referee for the match",
      "Add Assistant Referees",
      "Add Fourth Official if required",
      "Officials receive their assignments",
      "Ensures proper match coverage",
    ],
  ),
  create_help_guide_step(
    18,
    "Prepare Match Lineups",
    "Set starting lineups and substitutes for upcoming fixtures.",
    "/fixture-lineups/create",
    [
      "Navigate to Fixture Lineups",
      "Select the fixture to prepare",
      "Choose starting XI (or appropriate number)",
      "Assign jersey numbers and positions",
      "Add substitute players",
      "Include team staff on the bench",
      "Lineups can be modified until match starts",
    ],
  ),
  create_help_guide_step(
    19,
    "Start a Live Game",
    "Begin live scoring and match management for a fixture.",
    "/live-games",
    [
      "Go to Live Games from the sidebar",
      "Or click 'Manage' on a fixture from Fixtures list",
      "Click 'Start Game' when ready",
      "The match clock begins automatically",
      "Current period is tracked (1st half, 2nd half, etc.)",
      "Both teams' lineups are displayed",
      "Score updates appear in real-time",
    ],
  ),
  create_help_guide_step(
    20,
    "Record Match Events",
    "Log goals, cards, substitutions, and other match events as they happen.",
    "/live-games",
    [
      "During a live game, use the event controls",
      "Record goals with scorer and time",
      "Log yellow and red cards",
      "Record substitutions (player in/out)",
      "Add assists if applicable",
      "Track injuries or stoppages",
      "All events are timestamped automatically",
    ],
  ),
  create_help_guide_step(
    21,
    "Manage Game Periods",
    "Control half-time, extra time, and period transitions during matches.",
    "/live-games",
    [
      "Use 'End Period' to conclude current period",
      "Start next period when teams are ready",
      "Half-time break is tracked automatically",
      "Add extra time if regulations require",
      "Penalty shootouts can be recorded",
      "Match duration is calculated precisely",
      "Period-by-period stats are maintained",
    ],
  ),
  create_help_guide_step(
    22,
    "Complete the Game",
    "Finalize the match and confirm the final result.",
    "/live-games",
    [
      "When all periods are complete, click 'End Game'",
      "Final score is locked and recorded",
      "Match status changes to 'Completed'",
      "Results are automatically added to standings",
      "Player statistics are updated",
      "Match report becomes available",
      "Competition table recalculates immediately",
    ],
  ),
  create_help_guide_step(
    23,
    "View Competition Results",
    "Check standings, results, and statistics for your competition.",
    "/competition-results",
    [
      "Navigate to Competition Results",
      "Select the competition to view",
      "See the current standings table",
      "Points, wins, draws, losses displayed",
      "Goal difference and goals scored/conceded",
      "Click teams to see their match history",
      "Track who's leading, who needs improvement",
    ],
  ),
];
