import { describe, expect, it, vi } from "vitest";

import {
  auto_generate_live_game_lineup,
  ensure_live_game_lineups_before_start,
  record_live_game_detail_event,
} from "./liveGameDetailActions";

describe("liveGameDetailActions", () => {
  type FixtureUseCases = Parameters<typeof record_live_game_detail_event>[7];
  type SelectedEventType = Parameters<typeof record_live_game_detail_event>[1];
  type AutoGeneratedFixture = Parameters<
    typeof auto_generate_live_game_lineup
  >[0];
  type PlayerMembershipUseCases = Parameters<
    typeof auto_generate_live_game_lineup
  >[2];
  type PlayerUseCases = Parameters<typeof auto_generate_live_game_lineup>[3];
  type FixtureLineupUseCases = Parameters<
    typeof auto_generate_live_game_lineup
  >[4];
  type EnsureFixture = Parameters<
    typeof ensure_live_game_lineups_before_start
  >[0];
  type EnsureHomePlayers = Parameters<
    typeof ensure_live_game_lineups_before_start
  >[1];
  type EnsureAwayPlayers = Parameters<
    typeof ensure_live_game_lineups_before_start
  >[2];
  type EnsureTeam = NonNullable<
    Parameters<typeof ensure_live_game_lineups_before_start>[3]
  >;

  it("records a live-game event using the selected event label when no description is supplied", async () => {
    const fixture_use_cases: Pick<FixtureUseCases, "record_game_event"> = {
      record_game_event: vi
        .fn()
        .mockResolvedValue({ success: true, data: { id: "fixture-1" } }),
    };
    const selected_event_type = {
      id: "goal",
      label: "Goal",
    } as SelectedEventType;

    await record_live_game_detail_event(
      "fixture-1",
      selected_event_type,
      18,
      "home",
      "Ada Stone",
      "",
      "",
      fixture_use_cases as FixtureUseCases,
    );

    expect(fixture_use_cases.record_game_event).toHaveBeenCalledWith(
      "fixture-1",
      expect.objectContaining({
        event_type: "goal",
        minute: 18,
        description: "Goal",
        player_name: "Ada Stone",
      }),
    );
  });

  it("auto-generates a lineup for active memberships through the shell export", async () => {
    const result = await auto_generate_live_game_lineup(
      {
        id: "fixture-1",
        organization_id: "organization-1",
      } as AutoGeneratedFixture,
      "team-1",
      {
        list: vi.fn().mockResolvedValue({
          success: true,
          data: {
            items: [
              { player_id: "player-1", status: "active", jersey_number: 9 },
            ],
          },
        }),
      } as unknown as PlayerMembershipUseCases,
      {
        get_by_id: vi.fn().mockResolvedValue({
          success: true,
          data: { id: "player-1", first_name: "Ada", last_name: "Stone" },
        }),
      } as unknown as PlayerUseCases,
      {
        create: vi.fn().mockResolvedValue({ success: true }),
      } as unknown as FixtureLineupUseCases,
    );

    expect(result).toBe(true);
  });

  it("returns the missing-lineups error through the shell export when auto-submission is disabled", async () => {
    const fixture = {
      home_team_id: "team-home",
      away_team_id: "team-away",
    } as EnsureFixture;
    const home_players: EnsureHomePlayers = [];
    const away_players: EnsureAwayPlayers = [];

    await expect(
      ensure_live_game_lineups_before_start(
        fixture,
        home_players,
        away_players,
        { name: "Lions" } as EnsureTeam,
        { name: "Tigers" } as EnsureTeam,
        false,
        {} as PlayerMembershipUseCases,
        {} as PlayerUseCases,
        {} as FixtureLineupUseCases,
      ),
    ).resolves.toEqual({
      success: false,
      error_message:
        "Both teams (Lions and Tigers) have not submitted their squads for this fixture. Please submit lineups before starting the game.",
    });
  });
});
