import { describe, expect, it, vi } from "vitest";

import {
  auto_generate_live_game_lineup,
  ensure_live_game_lineups_before_start,
  update_live_game_player_time_on,
} from "./liveGameDetailLineupActions";

describe("liveGameDetailLineupActions", () => {
  type UpdatedPlayers = Parameters<typeof update_live_game_player_time_on>[1];
  type FixtureLineupUseCases = Parameters<
    typeof update_live_game_player_time_on
  >[4];
  type AutoGeneratedFixture = Parameters<
    typeof auto_generate_live_game_lineup
  >[0];
  type PlayerMembershipUseCases = Parameters<
    typeof auto_generate_live_game_lineup
  >[2];
  type PlayerUseCases = Parameters<typeof auto_generate_live_game_lineup>[3];
  type EnsureFixture = Parameters<
    typeof ensure_live_game_lineups_before_start
  >[0];
  type EnsureHomePlayers = Parameters<
    typeof ensure_live_game_lineups_before_start
  >[1];
  type EnsureAwayPlayers = Parameters<
    typeof ensure_live_game_lineups_before_start
  >[2];
  type EnsureTeam = NonNullable<
    Parameters<typeof ensure_live_game_lineups_before_start>[3]
  >;

  function create_lineup_player(
    overrides: Partial<UpdatedPlayers[number]> = {},
  ): UpdatedPlayers[number] {
    return {
      id: "player-1",
      first_name: "Ada",
      last_name: "Stone",
      jersey_number: null,
      position: null,
      is_captain: false,
      is_substitute: false,
      time_on: undefined,
      ...overrides,
    };
  }

  it("updates only the selected player time-on value and persists the revised lineup", async () => {
    const fixture_lineup_use_cases: Pick<FixtureLineupUseCases, "update"> = {
      update: vi.fn().mockResolvedValue({ success: true }),
    };

    const result = await update_live_game_player_time_on(
      "lineup-1",
      [
        create_lineup_player({ id: "player-1", time_on: "present_at_start" }),
        create_lineup_player({ id: "player-2", time_on: "present_at_start" }),
      ],
      "player-2",
      "55",
      fixture_lineup_use_cases as FixtureLineupUseCases,
    );

    expect(fixture_lineup_use_cases.update).toHaveBeenCalledWith("lineup-1", {
      selected_players: [
        create_lineup_player({ id: "player-1", time_on: "present_at_start" }),
        create_lineup_player({ id: "player-2", time_on: "55" }),
      ],
    });
    expect(result).toEqual({
      success: true,
      updated_players: [
        create_lineup_player({ id: "player-1", time_on: "present_at_start" }),
        create_lineup_player({ id: "player-2", time_on: "55" }),
      ],
    });
  });

  it("auto-generates a lineup from active memberships and fills missing player details with fallbacks", async () => {
    const player_membership_use_cases: Pick<PlayerMembershipUseCases, "list"> =
      {
        list: vi.fn().mockResolvedValue({
          success: true,
          data: {
            items: [
              { player_id: "player-1", status: "active", jersey_number: 9 },
              { player_id: "player-2", status: "inactive", jersey_number: 12 },
              { player_id: "player-3", status: "active", jersey_number: null },
            ],
          },
        }),
      };
    const player_use_cases: Pick<PlayerUseCases, "get_by_id"> = {
      get_by_id: vi.fn().mockImplementation(async (player_id: string) =>
        player_id === "player-1"
          ? {
              success: true,
              data: { id: "player-1", first_name: "Ada", last_name: "Stone" },
            }
          : { success: false, error: "Missing" },
      ),
    };
    const fixture_lineup_use_cases: Pick<
      Parameters<typeof auto_generate_live_game_lineup>[4],
      "create"
    > = {
      create: vi.fn().mockResolvedValue({ success: true }),
    };

    const result = await auto_generate_live_game_lineup(
      {
        id: "fixture-1",
        organization_id: "organization-1",
      } as AutoGeneratedFixture,
      "team-1",
      player_membership_use_cases as PlayerMembershipUseCases,
      player_use_cases as PlayerUseCases,
      fixture_lineup_use_cases as Parameters<
        typeof auto_generate_live_game_lineup
      >[4],
    );

    expect(result).toBe(true);
    expect(fixture_lineup_use_cases.create).toHaveBeenCalledWith(
      expect.objectContaining({
        fixture_id: "fixture-1",
        team_id: "team-1",
        submitted_by: "auto-generated",
        notes: "Auto-generated lineup at game start",
        selected_players: [
          expect.objectContaining({
            id: "player-1",
            first_name: "Ada",
            last_name: "Stone",
            jersey_number: 9,
          }),
          expect.objectContaining({
            id: "player-3",
            first_name: "Unknown",
            last_name: "Player",
            jersey_number: null,
          }),
        ],
      }),
    );
  });

  it("returns a descriptive error when both lineups are missing and auto-submission is disabled", async () => {
    const fixture = {
      home_team_id: "team-home",
      away_team_id: "team-away",
    } as EnsureFixture;
    const home_team = { name: "Lions" } as EnsureTeam;
    const away_team = { name: "Tigers" } as EnsureTeam;
    const home_players: EnsureHomePlayers = [];
    const away_players: EnsureAwayPlayers = [];

    await expect(
      ensure_live_game_lineups_before_start(
        fixture,
        home_players,
        away_players,
        home_team,
        away_team,
        false,
        {} as PlayerMembershipUseCases,
        {} as PlayerUseCases,
        {} as Parameters<typeof auto_generate_live_game_lineup>[4],
      ),
    ).resolves.toEqual({
      success: false,
      error_message:
        "Both teams (Lions and Tigers) have not submitted their squads for this fixture. Please submit lineups before starting the game.",
    });
  });

  it("auto-generates a missing lineup and asks the caller to reload before game start", async () => {
    const player_membership_use_cases: Pick<PlayerMembershipUseCases, "list"> =
      {
        list: vi.fn().mockResolvedValue({
          success: true,
          data: {
            items: [
              { player_id: "player-1", status: "active", jersey_number: 9 },
            ],
          },
        }),
      };
    const player_use_cases: Pick<PlayerUseCases, "get_by_id"> = {
      get_by_id: vi.fn().mockResolvedValue({
        success: true,
        data: { id: "player-1", first_name: "Ada", last_name: "Stone" },
      }),
    };
    const fixture_lineup_use_cases: Pick<
      Parameters<typeof auto_generate_live_game_lineup>[4],
      "create"
    > = {
      create: vi.fn().mockResolvedValue({ success: true }),
    };

    await expect(
      ensure_live_game_lineups_before_start(
        {
          id: "fixture-1",
          organization_id: "organization-1",
          home_team_id: "team-home",
          away_team_id: "team-away",
        } as EnsureFixture,
        [],
        [create_lineup_player({ id: "away-player" })],
        { name: "Lions" } as EnsureTeam,
        { name: "Tigers" } as EnsureTeam,
        true,
        player_membership_use_cases as PlayerMembershipUseCases,
        player_use_cases as PlayerUseCases,
        fixture_lineup_use_cases as Parameters<
          typeof auto_generate_live_game_lineup
        >[4],
      ),
    ).resolves.toEqual({ success: true, reloaded_required: true });
    expect(fixture_lineup_use_cases.create).toHaveBeenCalledTimes(1);
  });
});
