import type { Player } from "../../../core/entities/Player";
import type { ScalarValueInput } from "../../../core/types/DomainScalars";
import type { PositionIds } from "./seedPlayerIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_players_group5(
  positions: PositionIds,
  organization_id: ScalarValueInput<Omit<Player, "gender_id">["organization_id"]>,
  now: Omit<Player, "gender_id">["created_at"],
): import("$lib/core/types/DomainScalars").ScalarInput<Omit<Player, "gender_id">>[] {
  return [
    {
      id: SEED_PLAYER_IDS.KAMPALA_P4,
      first_name: "Henry",
      last_name: "Kawuki",
      email: "henry.kawuki@kampalahc.ug",
      phone: "+256-700-200-004",
      date_of_birth: "1996-06-14",
      position_id: positions.lb,
      organization_id,
      height_cm: 187,
      weight_kg: 82,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Joyce Kawuki",
      emergency_contact_phone: "+256-700-200-104",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P5,
      first_name: "Janet",
      last_name: "Atim",
      email: "janet.atim@kampalahc.ug",
      phone: "+256-700-200-005",
      date_of_birth: "1998-09-22",
      position_id: positions.rb,
      organization_id,
      height_cm: 166,
      weight_kg: 61,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Robert Atim",
      emergency_contact_phone: "+256-700-200-105",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P6,
      first_name: "Samuel",
      last_name: "Ojok",
      email: "samuel.ojok@kampalahc.ug",
      phone: "+256-700-200-006",
      date_of_birth: "1997-01-28",
      position_id: positions.cm,
      organization_id,
      height_cm: 178,
      weight_kg: 74,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Helen Ojok",
      emergency_contact_phone: "+256-700-200-106",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P7,
      first_name: "Rebecca",
      last_name: "Nanyonjo",
      email: "rebecca.nanyonjo@kampalahc.ug",
      phone: "+256-700-200-007",
      date_of_birth: "1999-04-05",
      position_id: positions.lm,
      organization_id,
      height_cm: 169,
      weight_kg: 63,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Paul Nanyonjo",
      emergency_contact_phone: "+256-700-200-107",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P8,
      first_name: "Andrew",
      last_name: "Okoth",
      email: "andrew.okoth@kampalahc.ug",
      phone: "+256-700-200-008",
      date_of_birth: "1995-07-19",
      position_id: positions.rm,
      organization_id,
      height_cm: 182,
      weight_kg: 77,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Grace Okoth",
      emergency_contact_phone: "+256-700-200-108",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P9,
      first_name: "Doreen",
      last_name: "Akello",
      email: "doreen.akello@kampalahc.ug",
      phone: "+256-700-200-009",
      date_of_birth: "1998-10-11",
      position_id: positions.lw,
      organization_id,
      height_cm: 164,
      weight_kg: 58,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Simon Akello",
      emergency_contact_phone: "+256-700-200-109",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P10,
      first_name: "Vincent",
      last_name: "Otim",
      email: "vincent.otim@kampalahc.ug",
      phone: "+256-700-200-010",
      date_of_birth: "1996-12-03",
      position_id: positions.rw,
      organization_id,
      height_cm: 177,
      weight_kg: 72,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Rose Otim",
      emergency_contact_phone: "+256-700-200-110",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KAMPALA_P11,
      first_name: "Angela",
      last_name: "Nabirye",
      email: "angela.nabirye@kampalahc.ug",
      phone: "+256-700-200-011",
      date_of_birth: "1997-03-16",
      position_id: positions.cf,
      organization_id,
      height_cm: 168,
      weight_kg: 62,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "James Nabirye",
      emergency_contact_phone: "+256-700-200-111",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
