import type { FixtureLineup } from "../../../core/entities/FixtureLineup";
import {
  SEED_FIXTURE_LINEUP_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_FIXTURE_IDS,
  SEED_TEAM_IDS,
  generate_current_timestamp,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_lineups_part13(): FixtureLineup[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_LINEUP_IDS.EASTER_CUP_GROUP_B_2_HOME_LINEUP,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      fixture_id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_B_2,
      team_id: SEED_TEAM_IDS.WANANCHI_HC,
      selected_players: [
        {
          id: SEED_PLAYER_IDS.WANANCHI_P4,
          first_name: "Martin",
          last_name: "Omara",
          jersey_number: 1,
          position: "Goalkeeper",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P5,
          first_name: "Susan",
          last_name: "Angom",
          jersey_number: 4,
          position: "Left Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P6,
          first_name: "Edward",
          last_name: "Otema",
          jersey_number: 5,
          position: "Sweeper",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P7,
          first_name: "Jennifer",
          last_name: "Achieng",
          jersey_number: 6,
          position: "Right Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P8,
          first_name: "David",
          last_name: "Obua",
          jersey_number: 7,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.CHRISTINE_AMONGI,
          first_name: "Christine",
          last_name: "Amongi",
          jersey_number: 8,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.JUDITH_NAKATO,
          first_name: "Judith",
          last_name: "Nakato",
          jersey_number: 9,
          position: "Left Wing",
          is_captain: true,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.PETER_DRAGO,
          first_name: "Peter",
          last_name: "Drago",
          jersey_number: 11,
          position: "Center Forward",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P10,
          first_name: "Joseph",
          last_name: "Okumu",
          jersey_number: 12,
          position: "Forward",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P9,
          first_name: "Prossy",
          last_name: "Odongo",
          jersey_number: 10,
          position: "Right Wing",
          is_captain: false,
          is_substitute: true,
          time_on: "50",
        },
        {
          id: SEED_PLAYER_IDS.WANANCHI_P11,
          first_name: "Brenda",
          last_name: "Otieno",
          jersey_number: 13,
          position: "Midfielder",
          is_captain: false,
          is_substitute: true,
          time_on: "didnt_play",
        },
      ],
      status: "locked",
      submitted_by: "admin",
      submitted_at: "2026-04-03T11:00:00Z",
      notes: "Wananchi lineup - Easter Cup Group B Match 2",
      created_at: now,
      updated_at: now,
    },
  ];
}
