import type { FixtureLineup } from "../../../core/entities/FixtureLineup";
import {
  generate_current_timestamp,
  SEED_FIXTURE_IDS,
  SEED_FIXTURE_LINEUP_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_lineups_part17(): import("$lib/core/types/DomainScalars").ScalarInput<FixtureLineup>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_LINEUP_IDS.EASTER_CUP_SEMI_1_HOME_LINEUP,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      fixture_id: SEED_FIXTURE_IDS.EASTER_CUP_SEMI_1,
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      selected_players: [
        {
          id: SEED_PLAYER_IDS.JOSEPH_MUSOKE,
          first_name: "Joseph",
          last_name: "Musoke",
          jersey_number: 1,
          position: "Goalkeeper",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P4,
          first_name: "Alex",
          last_name: "Kibuuka",
          jersey_number: 4,
          position: "Left Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P5,
          first_name: "Simon",
          last_name: "Otim",
          jersey_number: 5,
          position: "Sweeper",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P6,
          first_name: "Martha",
          last_name: "Adong",
          jersey_number: 6,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P7,
          first_name: "Paul",
          last_name: "Mugisha",
          jersey_number: 7,
          position: "Left Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P8,
          first_name: "Irene",
          last_name: "Nassanga",
          jersey_number: 8,
          position: "Right Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.DENIS_ONYANGO,
          first_name: "Denis",
          last_name: "Onyango",
          jersey_number: 9,
          position: "Forward",
          is_captain: true,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.BRIAN_SSALI,
          first_name: "Brian",
          last_name: "Ssali",
          jersey_number: 10,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P9,
          first_name: "Richard",
          last_name: "Okware",
          jersey_number: 11,
          position: "Left Wing",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P11,
          first_name: "Charles",
          last_name: "Opolot",
          jersey_number: 13,
          position: "Center Forward",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.WEATHERHEAD_P10,
          first_name: "Gloria",
          last_name: "Apio",
          jersey_number: 12,
          position: "Right Wing",
          is_captain: false,
          is_substitute: true,
          time_on: "70",
        },
      ],
      status: "locked",
      submitted_by: "admin",
      submitted_at: "2026-04-05T09:00:00Z",
      notes: "Weatherhead lineup - Easter Cup Semi Final 1",
      created_at: now,
      updated_at: now,
    },
  ];
}
