import type { Player } from "../../../core/entities/Player";
import { SEED_ORGANIZATION_IDS, generate_current_timestamp } from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";
import type { PositionIds } from "./seedPlayerIds";

export function create_seed_players_group7(
  positions: PositionIds,
  organization_id: string,
  now: string,
): Omit<Player, "gender_id">[] {
  return [
    {
      id: SEED_PLAYER_IDS.WANANCHI_P4,
      first_name: "Martin",
      last_name: "Omara",
      email: "martin.omara@wananchihc.ug",
      phone: "+256-700-400-004",
      date_of_birth: "1996-01-17",
      position_id: positions.lb,
      organization_id,
      height_cm: 186,
      weight_kg: 81,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Grace Omara",
      emergency_contact_phone: "+256-700-400-104",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P5,
      first_name: "Susan",
      last_name: "Angom",
      email: "susan.angom@wananchihc.ug",
      phone: "+256-700-400-005",
      date_of_birth: "1998-04-24",
      position_id: positions.rb,
      organization_id,
      height_cm: 167,
      weight_kg: 61,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Paul Angom",
      emergency_contact_phone: "+256-700-400-105",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P6,
      first_name: "Edward",
      last_name: "Otema",
      email: "edward.otema@wananchihc.ug",
      phone: "+256-700-400-006",
      date_of_birth: "1995-07-11",
      position_id: positions.cm,
      organization_id,
      height_cm: 177,
      weight_kg: 73,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Rose Otema",
      emergency_contact_phone: "+256-700-400-106",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P7,
      first_name: "Jennifer",
      last_name: "Achieng",
      email: "jennifer.achieng@wananchihc.ug",
      phone: "+256-700-400-007",
      date_of_birth: "1999-10-06",
      position_id: positions.lm,
      organization_id,
      height_cm: 164,
      weight_kg: 58,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Simon Achieng",
      emergency_contact_phone: "+256-700-400-107",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P8,
      first_name: "David",
      last_name: "Obua",
      email: "david.obua@wananchihc.ug",
      phone: "+256-700-400-008",
      date_of_birth: "1996-08-19",
      position_id: positions.rm,
      organization_id,
      height_cm: 181,
      weight_kg: 76,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Sarah Obua",
      emergency_contact_phone: "+256-700-400-108",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P9,
      first_name: "Prossy",
      last_name: "Odongo",
      email: "prossy.odongo@wananchihc.ug",
      phone: "+256-700-400-009",
      date_of_birth: "1997-11-28",
      position_id: positions.lw,
      organization_id,
      height_cm: 165,
      weight_kg: 59,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "James Odongo",
      emergency_contact_phone: "+256-700-400-109",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P10,
      first_name: "Joseph",
      last_name: "Okumu",
      email: "joseph.okumu@wananchihc.ug",
      phone: "+256-700-400-010",
      date_of_birth: "1995-02-14",
      position_id: positions.rw,
      organization_id,
      height_cm: 178,
      weight_kg: 74,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Mary Okumu",
      emergency_contact_phone: "+256-700-400-110",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.WANANCHI_P11,
      first_name: "Brenda",
      last_name: "Otieno",
      email: "brenda.otieno@wananchihc.ug",
      phone: "+256-700-400-011",
      date_of_birth: "1998-05-07",
      position_id: positions.cf,
      organization_id,
      height_cm: 169,
      weight_kg: 63,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Charles Otieno",
      emergency_contact_phone: "+256-700-400-111",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
