import type { Fixture } from "../../../core/entities/Fixture";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_FIXTURE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_STAGE_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_fixtures_part7(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): import("$lib/core/types/DomainScalars").ScalarInput<Fixture>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_A_3,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 3,
      round_name: "Group Stage",
      home_team_id: SEED_TEAM_IDS.KAMPALA_HC,
      away_team_id: SEED_TEAM_IDS.SIMBA_HC,
      venue: "Lugogo Hockey Stadium",
      scheduled_date: "2026-04-04",
      scheduled_time: "10:00",
      home_team_score: 2,
      away_team_score: 1,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_ga3_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-04T10:00:00Z",
        },
        {
          id: "game_event_ga3_2",
          event_type: "goal",
          minute: 10,
          stoppage_time_minute: null,
          team_side: "away",
          player_name: "Simba Forward",
          secondary_player_name: "",
          description: "Early goal for Simba",
          recorded_at: "2026-04-04T10:10:00Z",
        },
        {
          id: "game_event_ga3_3",
          event_type: "goal",
          minute: 25,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Ronald Mukiibi",
          secondary_player_name: "",
          description: "Kampala level through Ronald Mukiibi",
          recorded_at: "2026-04-04T10:25:00Z",
        },
        {
          id: "game_event_ga3_4",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 1-1",
          recorded_at: "2026-04-04T10:35:00Z",
        },
        {
          id: "game_event_ga3_5",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-04T10:50:00Z",
        },
        {
          id: "game_event_ga3_6",
          event_type: "goal",
          minute: 62,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Sarah Namugwanya",
          secondary_player_name: "Ronald Mukiibi",
          description: "Kampala take the lead through Sarah Namugwanya",
          recorded_at: "2026-04-04T11:17:00Z",
        },
        {
          id: "game_event_ga3_7",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 2-1",
          recorded_at: "2026-04-04T11:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 3,
      notes:
        "Easter Cup Group A - Kampala edge Simba 2-1 to secure second place",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_POOL_STAGE,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
