import type { Venue } from "../../../core/entities/Venue";
import type { ScalarValueInput } from "../../../core/types/DomainScalars";
import { DEFAULT_VENUE_IMAGE } from "../../../core/entities/Venue";
import { generate_current_timestamp, SEED_VENUE_IDS } from "./seedIds";

export function create_seed_venues(
  organization_id: ScalarValueInput<Venue["organization_id"]>,
): import("$lib/core/types/DomainScalars").ScalarInput<Venue>[] {
  const now = generate_current_timestamp();
  return [
    {
      id: SEED_VENUE_IDS.LUGOGO_HOCKEY_STADIUM,
      organization_id,
      name: "Lugogo Hockey Stadium",
      short_name: "LHS",
      address: "Lugogo Sports Complex",
      city: "Kampala",
      country: "Uganda",
      capacity: 5000,
      surface_type: "artificial_turf",
      has_lighting: true,
      has_parking: true,
      contact_email: "info@lugogohockey.ug",
      contact_phone: "+256-414-123-456",
      website: "https://ugandahockey.org/lugogo",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_VENUE_IDS.KYAMBOGO_HOCKEY_PITCH,
      organization_id,
      name: "Kyambogo Hockey Pitch",
      short_name: "KHP",
      address: "Kyambogo University",
      city: "Kampala",
      country: "Uganda",
      capacity: 2000,
      surface_type: "artificial_turf",
      has_lighting: true,
      has_parking: true,
      contact_email: "sports@kyu.ac.ug",
      contact_phone: "+256-414-234-567",
      website: "https://kyu.ac.ug/sports",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_VENUE_IDS.MAKERERE_HOCKEY_GROUND,
      organization_id,
      name: "Makerere Hockey Ground",
      short_name: "MHG",
      address: "Makerere University",
      city: "Kampala",
      country: "Uganda",
      capacity: 3000,
      surface_type: "artificial_turf",
      has_lighting: true,
      has_parking: true,
      contact_email: "sports@mak.ac.ug",
      contact_phone: "+256-414-345-678",
      website: "https://mak.ac.ug/sports",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_VENUE_IDS.ENTEBBE_SPORTS_CLUB,
      organization_id,
      name: "Entebbe Sports Club",
      short_name: "ESC",
      address: "Airport Road",
      city: "Entebbe",
      country: "Uganda",
      capacity: 1500,
      surface_type: "grass",
      has_lighting: true,
      has_parking: true,
      contact_email: "info@entebbesc.ug",
      contact_phone: "+256-414-456-789",
      website: "https://entebbesc.ug",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_VENUE_IDS.JINJA_HOCKEY_GROUND,
      organization_id,
      name: "Jinja Hockey Ground",
      short_name: "JHG",
      address: "Main Street",
      city: "Jinja",
      country: "Uganda",
      capacity: 2500,
      surface_type: "artificial_turf",
      has_lighting: true,
      has_parking: true,
      contact_email: "info@jinjahockey.ug",
      contact_phone: "+256-434-567-890",
      website: "https://jinjahockey.ug",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
