import type { GameEvent } from "../../../core/entities/Fixture";

export const GAME_EVENTS_COMPLETED_HOCKEY_GAME: GameEvent[] = [
  {
    id: "game_event_seed_1",
    event_type: "period_start",
    minute: 0,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "First half started",
    recorded_at: "2025-01-15T15:00:00Z",
  },
  {
    id: "game_event_seed_2",
    event_type: "goal",
    minute: 12,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Daniel Wasswa",
    secondary_player_name: "Moses Alowo",
    description: "Goal by Daniel Wasswa assisted by Moses Alowo",
    recorded_at: "2025-01-15T15:12:00Z",
  },
  {
    id: "game_event_seed_3",
    event_type: "goal",
    minute: 23,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Judith Nakato",
    secondary_player_name: "Peter Drago",
    description: "Goal by Judith Nakato assisted by Peter Drago",
    recorded_at: "2025-01-15T15:23:00Z",
  },
  {
    id: "game_event_seed_4",
    event_type: "period_end",
    minute: 35,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "First half ended. Score: 1-1",
    recorded_at: "2025-01-15T15:35:00Z",
  },
  {
    id: "game_event_seed_5",
    event_type: "period_start",
    minute: 35,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "Second half started",
    recorded_at: "2025-01-15T15:50:00Z",
  },
  {
    id: "game_event_seed_6",
    event_type: "penalty_scored",
    minute: 38,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "George Mugabi",
    secondary_player_name: "",
    description: "Penalty corner goal by George Mugabi",
    recorded_at: "2025-01-15T15:53:00Z",
  },
  {
    id: "game_event_seed_7",
    event_type: "yellow_card",
    minute: 42,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Moses Alowo",
    secondary_player_name: "",
    description: "Yellow card to Moses Alowo for obstruction",
    recorded_at: "2025-01-15T15:57:00Z",
  },
  {
    id: "game_event_seed_8",
    event_type: "substitution",
    minute: 45,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Betty Owori",
    secondary_player_name: "Patrick Ochieng",
    description: "Betty Owori replaced Patrick Ochieng",
    recorded_at: "2025-01-15T16:00:00Z",
  },
  {
    id: "game_event_seed_9",
    event_type: "yellow_card",
    minute: 51,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "David Obua",
    secondary_player_name: "",
    description: "Yellow card to David Obua for dangerous tackle",
    recorded_at: "2025-01-15T16:06:00Z",
  },
  {
    id: "game_event_seed_10",
    event_type: "substitution",
    minute: 52,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Prossy Odongo",
    secondary_player_name: "Jennifer Achieng",
    description: "Prossy Odongo replaced Jennifer Achieng",
    recorded_at: "2025-01-15T16:07:00Z",
  },
  {
    id: "game_event_seed_11",
    event_type: "goal",
    minute: 55,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Peter Drago",
    secondary_player_name: "Christine Amongi",
    description: "Goal by Peter Drago assisted by Christine Amongi",
    recorded_at: "2025-01-15T16:10:00Z",
  },
  {
    id: "game_event_seed_12",
    event_type: "substitution",
    minute: 60,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Winnie Akumu",
    secondary_player_name: "Edith Ogwal",
    description: "Winnie Akumu replaced Edith Ogwal",
    recorded_at: "2025-01-15T16:15:00Z",
  },
  {
    id: "game_event_seed_13",
    event_type: "goal",
    minute: 68,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Carol Adoko",
    secondary_player_name: "George Mugabi",
    description: "Winning goal by Carol Adoko assisted by George Mugabi",
    recorded_at: "2025-01-15T16:23:00Z",
  },
  {
    id: "game_event_seed_14",
    event_type: "period_end",
    minute: 70,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "Match ended. Final score: 3-2",
    recorded_at: "2025-01-15T16:25:00Z",
  },
];
