import type { PlayerTeamMembership } from "../../../core/entities/PlayerTeamMembership";
import {
  generate_current_timestamp,
  SEED_ORGANIZATION_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_memberships_part5(): PlayerTeamMembership[] {
  const now = generate_current_timestamp();

  return [
    {
      id: "player_team_membership_default_61",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.MAKERERE_P8,
      team_id: SEED_TEAM_IDS.MAKERERE_UNIVERSITY_HC,
      start_date: "2024-01-01",
      jersey_number: 9,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_62",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.MAKERERE_P9,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 2,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_63",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.MAKERERE_P10,
      team_id: SEED_TEAM_IDS.MAKERERE_UNIVERSITY_HC,
      start_date: "2024-01-01",
      jersey_number: 12,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_64",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.MAKERERE_P11,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 3,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_65",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P4,
      team_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      start_date: "2024-01-01",
      jersey_number: 1,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_66",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P5,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 5,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_67",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P6,
      team_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      start_date: "2024-01-01",
      jersey_number: 5,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_68",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P7,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 6,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_69",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P8,
      team_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      start_date: "2024-01-01",
      jersey_number: 8,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_70",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P9,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 7,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_71",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P10,
      team_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      start_date: "2024-01-01",
      jersey_number: 11,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_72",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KYAMBOGO_P11,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 8,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_73",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.SIMBA_P4,
      team_id: SEED_TEAM_IDS.SIMBA_HC,
      start_date: "2024-01-01",
      jersey_number: 4,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_74",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.SIMBA_P5,
      team_id: SEED_TEAM_IDS.WANANCHI_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 10,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_75",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.SIMBA_P6,
      team_id: SEED_TEAM_IDS.SIMBA_HC,
      start_date: "2024-01-01",
      jersey_number: 6,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
