import type { Fixture } from "../../../core/entities/Fixture";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_FIXTURE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_STAGE_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_fixtures_part9(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): Fixture[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_B_3,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 3,
      round_name: "Group Stage",
      home_team_id: SEED_TEAM_IDS.ROCKETS_HC,
      away_team_id: SEED_TEAM_IDS.STRIKERS_HC,
      venue: "Kyambogo Hockey Pitch",
      scheduled_date: "2026-04-04",
      scheduled_time: "14:00",
      home_team_score: 3,
      away_team_score: 0,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_gb3_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-04T14:00:00Z",
        },
        {
          id: "game_event_gb3_2",
          event_type: "goal",
          minute: 8,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Daniel Wasswa",
          secondary_player_name: "Moses Alowo",
          description: "Rockets strike early through Daniel Wasswa",
          recorded_at: "2026-04-04T14:08:00Z",
        },
        {
          id: "game_event_gb3_3",
          event_type: "goal",
          minute: 29,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "George Mugabi",
          secondary_player_name: "",
          description: "George Mugabi penalty corner - Rockets 2-0",
          recorded_at: "2026-04-04T14:29:00Z",
        },
        {
          id: "game_event_gb3_4",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 2-0",
          recorded_at: "2026-04-04T14:35:00Z",
        },
        {
          id: "game_event_gb3_5",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-04T14:50:00Z",
        },
        {
          id: "game_event_gb3_6",
          event_type: "goal",
          minute: 61,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Carol Adoko",
          secondary_player_name: "Daniel Wasswa",
          description: "Rockets complete the rout - Carol Adoko finishes 3-0",
          recorded_at: "2026-04-04T15:16:00Z",
        },
        {
          id: "game_event_gb3_7",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 3-0",
          recorded_at: "2026-04-04T15:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 3,
      notes:
        "Easter Cup Group B - Rockets put three past Strikers to top the group",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_POOL_STAGE,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
