import type { Fixture } from "../../../core/entities/Fixture";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_FIXTURE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_STAGE_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_fixtures_part11(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): import("$lib/core/types/DomainScalars").ScalarInput<Fixture>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_SEMI_2,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 2,
      round_name: "Semi Finals",
      home_team_id: SEED_TEAM_IDS.ROCKETS_HC,
      away_team_id: SEED_TEAM_IDS.KAMPALA_HC,
      venue: "Lugogo Hockey Stadium",
      scheduled_date: "2026-04-05",
      scheduled_time: "16:00",
      home_team_score: 2,
      away_team_score: 1,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_sf2_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-05T16:00:00Z",
        },
        {
          id: "game_event_sf2_2",
          event_type: "goal",
          minute: 20,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Moses Alowo",
          secondary_player_name: "Daniel Wasswa",
          description: "Moses Alowo gives Rockets the lead",
          recorded_at: "2026-04-05T16:20:00Z",
        },
        {
          id: "game_event_sf2_3",
          event_type: "goal",
          minute: 33,
          stoppage_time_minute: 0,
          team_side: "away",
          player_name: "Ronald Mukiibi",
          secondary_player_name: "",
          description: "Kampala level through Ronald Mukiibi",
          recorded_at: "2026-04-05T16:33:00Z",
        },
        {
          id: "game_event_sf2_4",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 1-1",
          recorded_at: "2026-04-05T16:35:00Z",
        },
        {
          id: "game_event_sf2_5",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-05T16:50:00Z",
        },
        {
          id: "game_event_sf2_6",
          event_type: "goal",
          minute: 63,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "George Mugabi",
          secondary_player_name: "Carol Adoko",
          description: "George Mugabi fires Rockets into the final",
          recorded_at: "2026-04-05T17:18:00Z",
        },
        {
          id: "game_event_sf2_7",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 2-1",
          recorded_at: "2026-04-05T17:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 2,
      notes:
        "Easter Cup SF2 - Rockets edge past brave Kampala 2-1 in a thriller",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_SEMI_FINALS,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
