import type { Fixture } from "../../../core/entities/Fixture";
import {
  SEED_FIXTURE_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_COMPETITION_IDS,
  SEED_TEAM_IDS,
  SEED_STAGE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_VENUE_IDS,
  generate_current_timestamp,
} from "./seedIds";

export function create_seed_fixtures_part8(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): Fixture[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_B_2,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 2,
      round_name: "Group Stage",
      home_team_id: SEED_TEAM_IDS.WANANCHI_HC,
      away_team_id: SEED_TEAM_IDS.STRIKERS_HC,
      venue: "Kyambogo Hockey Pitch",
      scheduled_date: "2026-04-03",
      scheduled_time: "14:00",
      home_team_score: 1,
      away_team_score: 2,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_gb2_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-03T14:00:00Z",
        },
        {
          id: "game_event_gb2_2",
          event_type: "goal",
          minute: 15,
          stoppage_time_minute: null,
          team_side: "away",
          player_name: "Strikers Attacker",
          secondary_player_name: "",
          description: "Strikers take the lead",
          recorded_at: "2026-04-03T14:15:00Z",
        },
        {
          id: "game_event_gb2_3",
          event_type: "goal",
          minute: 28,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Judith Nakato",
          secondary_player_name: "",
          description: "Wananchi level through Judith Nakato",
          recorded_at: "2026-04-03T14:28:00Z",
        },
        {
          id: "game_event_gb2_4",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 1-1",
          recorded_at: "2026-04-03T14:35:00Z",
        },
        {
          id: "game_event_gb2_5",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-03T14:50:00Z",
        },
        {
          id: "game_event_gb2_6",
          event_type: "goal",
          minute: 54,
          stoppage_time_minute: null,
          team_side: "away",
          player_name: "Strikers Striker",
          secondary_player_name: "",
          description: "Strikers go back ahead - decisive goal",
          recorded_at: "2026-04-03T15:09:00Z",
        },
        {
          id: "game_event_gb2_7",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 1-2",
          recorded_at: "2026-04-03T15:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 2,
      notes: "Easter Cup Group B - Strikers win in a close contest 2-1",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_POOL_STAGE,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
