import type { FixtureLineup } from "../../../core/entities/FixtureLineup";
import {
  SEED_FIXTURE_LINEUP_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_FIXTURE_IDS,
  SEED_TEAM_IDS,
  generate_current_timestamp,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_lineups_part11(): FixtureLineup[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_LINEUP_IDS.EASTER_CUP_GROUP_A_3_HOME_LINEUP,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      fixture_id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_A_3,
      team_id: SEED_TEAM_IDS.KAMPALA_HC,
      selected_players: [
        {
          id: SEED_PLAYER_IDS.KAMPALA_P4,
          first_name: "Henry",
          last_name: "Kawuki",
          jersey_number: 1,
          position: "Goalkeeper",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.SARAH_NAMUGWANYA,
          first_name: "Sarah",
          last_name: "Namugwanya",
          jersey_number: 4,
          position: "Left Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P5,
          first_name: "Janet",
          last_name: "Atim",
          jersey_number: 5,
          position: "Right Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P6,
          first_name: "Samuel",
          last_name: "Ojok",
          jersey_number: 6,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P7,
          first_name: "Rebecca",
          last_name: "Nanyonjo",
          jersey_number: 7,
          position: "Left Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.PATRICIA_APOLOT,
          first_name: "Patricia",
          last_name: "Apolot",
          jersey_number: 8,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P8,
          first_name: "Andrew",
          last_name: "Okoth",
          jersey_number: 9,
          position: "Right Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P9,
          first_name: "Doreen",
          last_name: "Akello",
          jersey_number: 10,
          position: "Left Wing",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.RONALD_MUKIIBI,
          first_name: "Ronald",
          last_name: "Mukiibi",
          jersey_number: 11,
          position: "Center Forward",
          is_captain: true,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P10,
          first_name: "Vincent",
          last_name: "Otim",
          jersey_number: 12,
          position: "Right Wing",
          is_captain: false,
          is_substitute: true,
          time_on: "65",
        },
        {
          id: SEED_PLAYER_IDS.KAMPALA_P11,
          first_name: "Angela",
          last_name: "Nabirye",
          jersey_number: 13,
          position: "Midfielder",
          is_captain: false,
          is_substitute: true,
          time_on: "didnt_play",
        },
      ],
      status: "locked",
      submitted_by: "admin",
      submitted_at: "2026-04-04T09:00:00Z",
      notes: "Kampala lineup - Easter Cup Group A Match 3",
      created_at: now,
      updated_at: now,
    },
  ];
}
