import type { JerseyColor } from "../../../core/entities/JerseyColor";
import {
  SEED_JERSEY_COLOR_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_TEAM_IDS,
  SEED_COMPETITION_IDS,
  generate_current_timestamp,
} from "./seedIds";

export function create_seed_jersey_colors_part2(): JerseyColor[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_JERSEY_COLOR_IDS.UNIVERSITY_OFFICIAL_WHITE,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.UNIVERSITY_HOCKEY_CHAMPIONSHIP_2026,
      nickname: "Standard White",
      main_color: "#FFFFFF",
      secondary_color: "#1F2937",
      tertiary_color: "#16A34A",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.UNIVERSITY_OFFICIAL_ORANGE,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.UNIVERSITY_HOCKEY_CHAMPIONSHIP_2026,
      nickname: "Alternate Orange",
      main_color: "#EA580C",
      secondary_color: "#1F2937",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.WANANCHI_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.WANANCHI_HC,
      nickname: "Home Kit",
      main_color: "#16A34A",
      secondary_color: "#FFFFFF",
      tertiary_color: "#1F2937",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.WANANCHI_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.WANANCHI_HC,
      nickname: "Away Kit",
      main_color: "#FFFFFF",
      secondary_color: "#16A34A",
      tertiary_color: "#1F2937",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.MAKERERE_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.MAKERERE_UNIVERSITY_HC,
      nickname: "Home Kit",
      main_color: "#7C3AED",
      secondary_color: "#F3E8FF",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.MAKERERE_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.MAKERERE_UNIVERSITY_HC,
      nickname: "Away Kit",
      main_color: "#F3E8FF",
      secondary_color: "#7C3AED",
      tertiary_color: "#1F2937",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.KYAMBOGO_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      nickname: "Home Kit",
      main_color: "#0891B2",
      secondary_color: "#ECFEFF",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.KYAMBOGO_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      nickname: "Away Kit",
      main_color: "#ECFEFF",
      secondary_color: "#0891B2",
      tertiary_color: "#1F2937",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.SIMBA_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.SIMBA_HC,
      nickname: "Home Kit",
      main_color: "#EA580C",
      secondary_color: "#1F2937",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.SIMBA_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.SIMBA_HC,
      nickname: "Away Kit",
      main_color: "#1F2937",
      secondary_color: "#EA580C",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.STRIKERS_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.STRIKERS_HC,
      nickname: "Home Kit",
      main_color: "#DB2777",
      secondary_color: "#FDF2F8",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.STRIKERS_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.STRIKERS_HC,
      nickname: "Away Kit",
      main_color: "#FDF2F8",
      secondary_color: "#DB2777",
      tertiary_color: "#1F2937",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
