import type { Fixture } from "../../../core/entities/Fixture";
import {
  SEED_FIXTURE_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_COMPETITION_IDS,
  SEED_TEAM_IDS,
  SEED_STAGE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_VENUE_IDS,
  generate_current_timestamp,
} from "./seedIds";

export function create_seed_fixtures_part2(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): Fixture[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_A_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 1,
      round_name: "Group Stage",
      home_team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      away_team_id: SEED_TEAM_IDS.KAMPALA_HC,
      venue: "Lugogo Hockey Stadium",
      scheduled_date: "2026-04-01",
      scheduled_time: "14:00",
      home_team_score: 3,
      away_team_score: 1,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_ga1_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-01T14:00:00Z",
        },
        {
          id: "game_event_ga1_2",
          event_type: "goal",
          minute: 12,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Denis Onyango",
          secondary_player_name: "Brian Ssali",
          description: "Goal by Denis Onyango assisted by Brian Ssali",
          recorded_at: "2026-04-01T14:12:00Z",
        },
        {
          id: "game_event_ga1_3",
          event_type: "goal",
          minute: 22,
          stoppage_time_minute: null,
          team_side: "away",
          player_name: "Ronald Mukiibi",
          secondary_player_name: "",
          description: "Goal by Ronald Mukiibi - penalty stroke",
          recorded_at: "2026-04-01T14:22:00Z",
        },
        {
          id: "game_event_ga1_4",
          event_type: "goal",
          minute: 34,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Alex Kibuuka",
          secondary_player_name: "Denis Onyango",
          description: "Goal by Alex Kibuuka assisted by Denis Onyango",
          recorded_at: "2026-04-01T14:34:00Z",
        },
        {
          id: "game_event_ga1_5",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 2-1",
          recorded_at: "2026-04-01T14:35:00Z",
        },
        {
          id: "game_event_ga1_6",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-01T14:50:00Z",
        },
        {
          id: "game_event_ga1_7",
          event_type: "goal",
          minute: 67,
          stoppage_time_minute: null,
          team_side: "home",
          player_name: "Paul Mugisha",
          secondary_player_name: "Alex Kibuuka",
          description: "Goal by Paul Mugisha - seals the win",
          recorded_at: "2026-04-01T15:02:00Z",
        },
        {
          id: "game_event_ga1_8",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: null,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 3-1",
          recorded_at: "2026-04-01T15:05:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 1,
      notes: "Easter Cup 2026 Group A - Weatherhead edge past Kampala 3-1",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_POOL_STAGE,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_FIXTURE_IDS.HOCKEY_FIXTURE_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.UNIVERSITY_HOCKEY_CHAMPIONSHIP_2026,
      round_number: 1,
      round_name: "Opening Round",
      home_team_id: SEED_TEAM_IDS.MAKERERE_UNIVERSITY_HC,
      away_team_id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      venue: "Makerere Hockey Ground",
      scheduled_date: three_weeks.toISOString().split("T")[0],
      scheduled_time: "10:00",
      home_team_score: null,
      away_team_score: null,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [],
      current_period: "pre_game",
      current_minute: 0,
      match_day: 1,
      notes: "University Championship - Makerere vs Kyambogo rivalry match",
      stage_id: SEED_STAGE_IDS.UNIVERSITY_ROUND_ROBIN,
      status: "scheduled",
      created_at: now,
      updated_at: now,
    },
  ];
}
