import type { JerseyColor } from "../../../core/entities/JerseyColor";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_JERSEY_COLOR_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_jersey_colors_part1(): import("$lib/core/types/DomainScalars").ScalarInput<JerseyColor>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_JERSEY_COLOR_IDS.WEATHERHEAD_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      nickname: "Home Kit",
      main_color: "#1E3A8A",
      secondary_color: "#FFFFFF",
      tertiary_color: "#F59E0B",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.WEATHERHEAD_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      nickname: "Away Kit",
      main_color: "#FFFFFF",
      secondary_color: "#1E3A8A",
      tertiary_color: "#F59E0B",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.KAMPALA_HC_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.KAMPALA_HC,
      nickname: "Home Kit",
      main_color: "#DC2626",
      secondary_color: "#FBBF24",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.KAMPALA_HC_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.KAMPALA_HC,
      nickname: "Away Kit",
      main_color: "#FBBF24",
      secondary_color: "#DC2626",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.ROCKETS_HOME,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.ROCKETS_HC,
      nickname: "Home Kit",
      main_color: "#F59E0B",
      secondary_color: "#1F2937",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.ROCKETS_AWAY,
      holder_type: "team",
      holder_id: SEED_TEAM_IDS.ROCKETS_HC,
      nickname: "Away Kit",
      main_color: "#1F2937",
      secondary_color: "#F59E0B",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.EASTER_CUP_OFFICIAL_BLACK,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      nickname: "Standard Black",
      main_color: "#1F2937",
      secondary_color: "#FBBF24",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.EASTER_CUP_OFFICIAL_YELLOW,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      nickname: "Alternate Yellow",
      main_color: "#FBBF24",
      secondary_color: "#1F2937",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.UGANDA_CUP_OFFICIAL_BLACK,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.UGANDA_CUP_2026,
      nickname: "Standard Black",
      main_color: "#1F2937",
      secondary_color: "#FFFFFF",
      tertiary_color: "#F59E0B",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.UGANDA_CUP_OFFICIAL_GREEN,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.UGANDA_CUP_2026,
      nickname: "Alternate Green",
      main_color: "#16A34A",
      secondary_color: "#1F2937",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.NHL_OFFICIAL_GRAY,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.NATIONAL_HOCKEY_LEAGUE_2026,
      nickname: "Standard Gray",
      main_color: "#6B7280",
      secondary_color: "#1F2937",
      tertiary_color: "#FFFFFF",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_JERSEY_COLOR_IDS.NHL_OFFICIAL_NAVY,
      holder_type: "competition_official",
      holder_id: SEED_COMPETITION_IDS.NATIONAL_HOCKEY_LEAGUE_2026,
      nickname: "Alternate Navy",
      main_color: "#1E3A8A",
      secondary_color: "#FFFFFF",
      tertiary_color: "#6B7280",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
