import type { FixtureLineup } from "../../../core/entities/FixtureLineup";
import {
  generate_current_timestamp,
  SEED_FIXTURE_IDS,
  SEED_FIXTURE_LINEUP_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_lineups_part15(): FixtureLineup[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_LINEUP_IDS.EASTER_CUP_GROUP_B_3_HOME_LINEUP,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      fixture_id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_B_3,
      team_id: SEED_TEAM_IDS.ROCKETS_HC,
      selected_players: [
        {
          id: SEED_PLAYER_IDS.EMMANUEL_OKELLO,
          first_name: "Emmanuel",
          last_name: "Okello",
          jersey_number: 1,
          position: "Goalkeeper",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P4,
          first_name: "Kenneth",
          last_name: "Amuge",
          jersey_number: 4,
          position: "Left Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.DANIEL_WASSWA,
          first_name: "Daniel",
          last_name: "Wasswa",
          jersey_number: 5,
          position: "Sweeper",
          is_captain: true,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P5,
          first_name: "Edith",
          last_name: "Ogwal",
          jersey_number: 6,
          position: "Right Back",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.MOSES_ALOWO,
          first_name: "Moses",
          last_name: "Alowo",
          jersey_number: 7,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P6,
          first_name: "George",
          last_name: "Mugabi",
          jersey_number: 8,
          position: "Center Midfield",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P8,
          first_name: "Patrick",
          last_name: "Ochieng",
          jersey_number: 10,
          position: "Right Wing",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P10,
          first_name: "Dennis",
          last_name: "Olweny",
          jersey_number: 12,
          position: "Forward",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P11,
          first_name: "Carol",
          last_name: "Adoko",
          jersey_number: 13,
          position: "Center Forward",
          is_captain: false,
          is_substitute: false,
          time_on: "present_at_start",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P7,
          first_name: "Betty",
          last_name: "Owori",
          jersey_number: 9,
          position: "Left Wing",
          is_captain: false,
          is_substitute: true,
          time_on: "55",
        },
        {
          id: SEED_PLAYER_IDS.ROCKETS_P9,
          first_name: "Winnie",
          last_name: "Akumu",
          jersey_number: 11,
          position: "Midfielder",
          is_captain: false,
          is_substitute: true,
          time_on: "didnt_play",
        },
      ],
      status: "locked",
      submitted_by: "admin",
      submitted_at: "2026-04-04T11:00:00Z",
      notes: "Rockets lineup - Easter Cup Group B Match 3",
      created_at: now,
      updated_at: now,
    },
  ];
}
