import type { Fixture } from "../../../core/entities/Fixture";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_FIXTURE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_STAGE_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_fixtures_part6(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): import("$lib/core/types/DomainScalars").ScalarInput<Fixture>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_GROUP_A_2,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 2,
      round_name: "Group Stage",
      home_team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      away_team_id: SEED_TEAM_IDS.SIMBA_HC,
      venue: "Lugogo Hockey Stadium",
      scheduled_date: "2026-04-03",
      scheduled_time: "10:00",
      home_team_score: 2,
      away_team_score: 0,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_ga2_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-03T10:00:00Z",
        },
        {
          id: "game_event_ga2_2",
          event_type: "goal",
          minute: 18,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Alex Kibuuka",
          secondary_player_name: "Paul Mugisha",
          description: "Goal by Alex Kibuuka",
          recorded_at: "2026-04-03T10:18:00Z",
        },
        {
          id: "game_event_ga2_3",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 1-0",
          recorded_at: "2026-04-03T10:35:00Z",
        },
        {
          id: "game_event_ga2_4",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-03T10:50:00Z",
        },
        {
          id: "game_event_ga2_5",
          event_type: "goal",
          minute: 58,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Denis Onyango",
          secondary_player_name: "Brian Ssali",
          description: "Goal by Denis Onyango - Weatherhead double the lead",
          recorded_at: "2026-04-03T11:13:00Z",
        },
        {
          id: "game_event_ga2_6",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 2-0",
          recorded_at: "2026-04-03T11:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 2,
      notes:
        "Easter Cup Group A - Weatherhead keep clean sheet against Simba 2-0",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_POOL_STAGE,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
