import type { PlayerTeamMembership } from "../../../core/entities/PlayerTeamMembership";
import {
  generate_current_timestamp,
  SEED_ORGANIZATION_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_memberships_part3(): import("$lib/core/types/DomainScalars").ScalarInput<PlayerTeamMembership>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: "player_team_membership_default_31",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.WEATHERHEAD_P10,
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 11,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_32",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.WEATHERHEAD_P11,
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      start_date: "2024-01-01",
      jersey_number: 13,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_33",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P4,
      team_id: SEED_TEAM_IDS.KAMPALA_HC,
      start_date: "2024-01-01",
      jersey_number: 1,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_34",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P5,
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 5,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_35",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P6,
      team_id: SEED_TEAM_IDS.KAMPALA_HC,
      start_date: "2024-01-01",
      jersey_number: 6,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_36",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P7,
      team_id: SEED_TEAM_IDS.KAMPALA_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 2,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_37",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P8,
      team_id: SEED_TEAM_IDS.KAMPALA_HC,
      start_date: "2024-01-01",
      jersey_number: 9,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_38",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P9,
      team_id: SEED_TEAM_IDS.KAMPALA_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 3,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_39",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P10,
      team_id: SEED_TEAM_IDS.KAMPALA_HC,
      start_date: "2024-01-01",
      jersey_number: 12,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_40",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.KAMPALA_P11,
      team_id: SEED_TEAM_IDS.KAMPALA_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 4,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_41",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.ROCKETS_P4,
      team_id: SEED_TEAM_IDS.ROCKETS_HC,
      start_date: "2024-01-01",
      jersey_number: 4,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_42",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.ROCKETS_P5,
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 7,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_43",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.ROCKETS_P6,
      team_id: SEED_TEAM_IDS.ROCKETS_HC,
      start_date: "2024-01-01",
      jersey_number: 8,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_44",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.ROCKETS_P7,
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC_WOMEN,
      start_date: "2024-01-01",
      jersey_number: 8,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_45",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      player_id: SEED_PLAYER_IDS.ROCKETS_P8,
      team_id: SEED_TEAM_IDS.ROCKETS_HC,
      start_date: "2024-01-01",
      jersey_number: 10,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
