import { SEED_GENDER_IDS } from "./seedIds";

export const SEED_PLAYER_IDS = {
  DENIS_ONYANGO: "player_default_1",
  BRIAN_SSALI: "player_default_2",
  JOSEPH_MUSOKE: "player_default_3",
  RONALD_MUKIIBI: "player_default_4",
  SARAH_NAMUGWANYA: "player_default_5",
  PATRICIA_APOLOT: "player_default_6",
  DANIEL_WASSWA: "player_default_7",
  MOSES_ALOWO: "player_default_8",
  EMMANUEL_OKELLO: "player_default_9",
  JUDITH_NAKATO: "player_default_10",
  PETER_DRAGO: "player_default_11",
  CHRISTINE_AMONGI: "player_default_12",
  STEVEN_MUKASA: "player_default_13",
  HARRIET_NANDAWULA: "player_default_14",
  TIMOTHY_LUBEGA: "player_default_15",
  GRACE_ACHOLA: "player_default_16",
  ISAAC_KATO: "player_default_17",
  JANE_KASULE: "player_default_18",
  MICHAEL_OPIO: "player_default_19",
  RUTH_ACAN: "player_default_20",
  FRANCIS_BYEKWASO: "player_default_21",
  SHARON_NABATANZI: "player_default_22",
  ROBERT_KIGGUNDU: "player_default_23",
  FLORENCE_NAMUTEBI: "player_default_24",
  WEATHERHEAD_P4: "player_default_25",
  WEATHERHEAD_P5: "player_default_26",
  WEATHERHEAD_P6: "player_default_27",
  WEATHERHEAD_P7: "player_default_28",
  WEATHERHEAD_P8: "player_default_29",
  WEATHERHEAD_P9: "player_default_30",
  WEATHERHEAD_P10: "player_default_31",
  WEATHERHEAD_P11: "player_default_32",
  KAMPALA_P4: "player_default_33",
  KAMPALA_P5: "player_default_34",
  KAMPALA_P6: "player_default_35",
  KAMPALA_P7: "player_default_36",
  KAMPALA_P8: "player_default_37",
  KAMPALA_P9: "player_default_38",
  KAMPALA_P10: "player_default_39",
  KAMPALA_P11: "player_default_40",
  ROCKETS_P4: "player_default_41",
  ROCKETS_P5: "player_default_42",
  ROCKETS_P6: "player_default_43",
  ROCKETS_P7: "player_default_44",
  ROCKETS_P8: "player_default_45",
  ROCKETS_P9: "player_default_46",
  ROCKETS_P10: "player_default_47",
  ROCKETS_P11: "player_default_48",
  WANANCHI_P4: "player_default_49",
  WANANCHI_P5: "player_default_50",
  WANANCHI_P6: "player_default_51",
  WANANCHI_P7: "player_default_52",
  WANANCHI_P8: "player_default_53",
  WANANCHI_P9: "player_default_54",
  WANANCHI_P10: "player_default_55",
  WANANCHI_P11: "player_default_56",
  MAKERERE_P4: "player_default_57",
  MAKERERE_P5: "player_default_58",
  MAKERERE_P6: "player_default_59",
  MAKERERE_P7: "player_default_60",
  MAKERERE_P8: "player_default_61",
  MAKERERE_P9: "player_default_62",
  MAKERERE_P10: "player_default_63",
  MAKERERE_P11: "player_default_64",
  KYAMBOGO_P4: "player_default_65",
  KYAMBOGO_P5: "player_default_66",
  KYAMBOGO_P6: "player_default_67",
  KYAMBOGO_P7: "player_default_68",
  KYAMBOGO_P8: "player_default_69",
  KYAMBOGO_P9: "player_default_70",
  KYAMBOGO_P10: "player_default_71",
  KYAMBOGO_P11: "player_default_72",
  SIMBA_P4: "player_default_73",
  SIMBA_P5: "player_default_74",
  SIMBA_P6: "player_default_75",
  SIMBA_P7: "player_default_76",
  SIMBA_P8: "player_default_77",
  SIMBA_P9: "player_default_78",
  SIMBA_P10: "player_default_79",
  SIMBA_P11: "player_default_80",
  STRIKERS_P4: "player_default_81",
  STRIKERS_P5: "player_default_82",
  STRIKERS_P6: "player_default_83",
  STRIKERS_P7: "player_default_84",
  STRIKERS_P8: "player_default_85",
  STRIKERS_P9: "player_default_86",
  STRIKERS_P10: "player_default_87",
  STRIKERS_P11: "player_default_88",
  ROCKETS_WOMEN_P9: "player_default_89",
  ROCKETS_WOMEN_P10: "player_default_90",
  ROCKETS_WOMEN_P11: "player_default_91",
};

export interface PositionIds {
  gk: string;
  sw: string;
  cb: string;
  lb: string;
  rb: string;
  cdm: string;
  cm: string;
  lm: string;
  rm: string;
  lw: string;
  rw: string;
  cf: string;
}

const FEMALE_SEED_FIRST_NAMES = new Set<string>([
  "Sarah",
  "Patricia",
  "Judith",
  "Christine",
  "Harriet",
  "Grace",
  "Jane",
  "Ruth",
  "Sharon",
  "Florence",
  "Martha",
  "Irene",
  "Susan",
  "Mary",
  "Gloria",
  "Diana",
  "Evelyn",
  "Anita",
  "Eva",
  "Lydia",
  "Miriam",
  "Dorothy",
  "Agnes",
  "Prossy",
  "Janet",
  "Rebecca",
  "Doreen",
  "Angela",
  "Edith",
  "Betty",
  "Winnie",
  "Carol",
  "Jennifer",
  "Brenda",
  "Esther",
  "Lillian",
  "Rita",
  "Joy",
  "Phiona",
  "Mercy",
  "Sandra",
  "Sylvia",
  "Stella",
  "Joyce",
  "Beatrice",
  "Alice",
]);

export function resolve_seed_gender_id_for_first_name(
  first_name: string,
): string {
  if (FEMALE_SEED_FIRST_NAMES.has(first_name)) {
    return SEED_GENDER_IDS.FEMALE;
  }
  return SEED_GENDER_IDS.MALE;
}
