import type { GameEvent } from "../../../core/entities/Fixture";

export const GAME_EVENTS_COMPLETED_GAME_2: GameEvent[] = [
  {
    id: "game_event_g2_1",
    event_type: "period_start",
    minute: 0,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "First half started",
    recorded_at: "2025-01-22T16:00:00Z",
  },
  {
    id: "game_event_g2_2",
    event_type: "green_card",
    minute: 8,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Patricia Apolot",
    secondary_player_name: "",
    description: "Green card warning to Patricia Apolot for minor obstruction",
    recorded_at: "2025-01-22T16:08:00Z",
  },
  {
    id: "game_event_g2_3",
    event_type: "goal",
    minute: 15,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Denis Onyango",
    secondary_player_name: "Brian Ssali",
    description: "Goal by Denis Onyango assisted by Brian Ssali",
    recorded_at: "2025-01-22T16:15:00Z",
  },
  {
    id: "game_event_g2_4",
    event_type: "substitution",
    minute: 20,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Paul Mugisha",
    secondary_player_name: "Simon Otim",
    description: "Paul Mugisha replaced Simon Otim",
    recorded_at: "2025-01-22T16:20:00Z",
  },
  {
    id: "game_event_g2_5",
    event_type: "yellow_card",
    minute: 28,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Alex Kibuuka",
    secondary_player_name: "",
    description: "Yellow card to Alex Kibuuka for dangerous tackle",
    recorded_at: "2025-01-22T16:28:00Z",
  },
  {
    id: "game_event_g2_6",
    event_type: "period_end",
    minute: 35,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "First half ended. Score: 1-0",
    recorded_at: "2025-01-22T16:35:00Z",
  },
  {
    id: "game_event_g2_7",
    event_type: "period_start",
    minute: 35,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "Second half started",
    recorded_at: "2025-01-22T16:50:00Z",
  },
  {
    id: "game_event_g2_8",
    event_type: "goal",
    minute: 42,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Ronald Mukiibi",
    secondary_player_name: "Sarah Namugwanya",
    description: "Goal by Ronald Mukiibi assisted by Sarah Namugwanya",
    recorded_at: "2025-01-22T16:57:00Z",
  },
  {
    id: "game_event_g2_9",
    event_type: "substitution",
    minute: 50,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Vincent Otim",
    secondary_player_name: "Samuel Ojok",
    description: "Vincent Otim replaced Samuel Ojok",
    recorded_at: "2025-01-22T17:05:00Z",
  },
  {
    id: "game_event_g2_10",
    event_type: "red_card",
    minute: 55,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Andrew Okoth",
    secondary_player_name: "",
    description: "Red card to Andrew Okoth for violent conduct - sent off",
    recorded_at: "2025-01-22T17:10:00Z",
  },
  {
    id: "game_event_g2_11",
    event_type: "penalty_scored",
    minute: 62,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Charles Opolot",
    secondary_player_name: "",
    description: "Penalty corner goal by Charles Opolot",
    recorded_at: "2025-01-22T17:17:00Z",
  },
  {
    id: "game_event_g2_12",
    event_type: "substitution",
    minute: 65,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Gloria Apio",
    secondary_player_name: "Irene Nassanga",
    description: "Gloria Apio replaced Irene Nassanga",
    recorded_at: "2025-01-22T17:20:00Z",
  },
  {
    id: "game_event_g2_13",
    event_type: "period_end",
    minute: 70,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "Match ended. Final score: 2-1",
    recorded_at: "2025-01-22T17:25:00Z",
  },
];
