import type { TeamStaff } from "../../../core/entities/TeamStaff";
import { DEFAULT_STAFF_AVATAR } from "../../../core/entities/TeamStaff";
import {
  generate_current_timestamp,
  SEED_ORGANIZATION_IDS,
  SEED_STAFF_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_team_staff(
  head_coach_role_id: string,
  assistant_coach_role_id: string,
  physio_role_id: string,
  team_manager_role_id: string,
): import("$lib/core/types/DomainScalars").ScalarInput<TeamStaff>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_STAFF_IDS.HEAD_COACH_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      first_name: "Emmanuel",
      last_name: "Lubwama",
      email: "emmanuel.lubwama@weatherheadhc.ug",
      phone: "+256-700-400-001",
      date_of_birth: "1975-04-12",
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      role_id: head_coach_role_id,
      nationality: "Uganda",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2020-01-15",
      employment_end_date: "",
      emergency_contact_name: "Grace Lubwama",
      emergency_contact_phone: "+256-700-400-101",
      notes: "FIH Level 2 Coach with 15 years of coaching experience",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.ASSISTANT_COACH_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      first_name: "Patrick",
      last_name: "Muwanga",
      email: "patrick.muwanga@weatherheadhc.ug",
      phone: "+256-700-400-002",
      date_of_birth: "1982-08-25",
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      role_id: assistant_coach_role_id,
      nationality: "Uganda",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2021-06-01",
      employment_end_date: "",
      emergency_contact_name: "Rebecca Muwanga",
      emergency_contact_phone: "+256-700-400-102",
      notes: "Former Uganda national team player",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.HEAD_COACH_2,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      first_name: "Joseph",
      last_name: "Kato",
      email: "joseph.kato@kampalahc.ug",
      phone: "+256-700-400-003",
      date_of_birth: "1970-11-30",
      team_id: SEED_TEAM_IDS.KAMPALA_HC,
      role_id: head_coach_role_id,
      nationality: "Uganda",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2019-08-01",
      employment_end_date: "",
      emergency_contact_name: "Alice Kato",
      emergency_contact_phone: "+256-700-400-103",
      notes: "Known for developing young hockey talent",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.PHYSIO_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      first_name: "Dorothy",
      last_name: "Nakato",
      email: "dorothy.nakato@weatherheadhc.ug",
      phone: "+256-700-400-004",
      date_of_birth: "1985-03-17",
      team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      role_id: physio_role_id,
      nationality: "Uganda",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2022-02-01",
      employment_end_date: "",
      emergency_contact_name: "David Nakato",
      emergency_contact_phone: "+256-700-400-104",
      notes: "Certified Sports Physiotherapist from Makerere University",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.MANAGER_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      first_name: "Richard",
      last_name: "Ssempala",
      email: "richard.ssempala@rocketshc.ug",
      phone: "+256-700-400-005",
      date_of_birth: "1968-07-08",
      team_id: SEED_TEAM_IDS.ROCKETS_HC,
      role_id: team_manager_role_id,
      nationality: "Uganda",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2015-01-10",
      employment_end_date: "",
      emergency_contact_name: "Martha Ssempala",
      emergency_contact_phone: "+256-700-400-105",
      notes: "10 years with the club, handles all administrative duties",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
