import type { Fixture } from "../../../core/entities/Fixture";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_FIXTURE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_STAGE_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_fixtures_part10(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): import("$lib/core/types/DomainScalars").ScalarInput<Fixture>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_SEMI_1,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 1,
      round_name: "Semi Finals",
      home_team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      away_team_id: SEED_TEAM_IDS.STRIKERS_HC,
      venue: "Lugogo Hockey Stadium",
      scheduled_date: "2026-04-05",
      scheduled_time: "12:00",
      home_team_score: 3,
      away_team_score: 0,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
      ],
      game_events: [
        {
          id: "game_event_sf1_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half started",
          recorded_at: "2026-04-05T12:00:00Z",
        },
        {
          id: "game_event_sf1_2",
          event_type: "goal",
          minute: 11,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Denis Onyango",
          secondary_player_name: "",
          description: "Denis Onyango opens the scoring",
          recorded_at: "2026-04-05T12:11:00Z",
        },
        {
          id: "game_event_sf1_3",
          event_type: "goal",
          minute: 31,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Alex Kibuuka",
          secondary_player_name: "Paul Mugisha",
          description: "Alex Kibuuka doubles Weatherhead's lead",
          recorded_at: "2026-04-05T12:31:00Z",
        },
        {
          id: "game_event_sf1_4",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 2-0",
          recorded_at: "2026-04-05T12:35:00Z",
        },
        {
          id: "game_event_sf1_5",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-05T12:50:00Z",
        },
        {
          id: "game_event_sf1_6",
          event_type: "goal",
          minute: 55,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Brian Ssali",
          secondary_player_name: "Denis Onyango",
          description: "Brian Ssali completes the rout",
          recorded_at: "2026-04-05T13:10:00Z",
        },
        {
          id: "game_event_sf1_7",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Match ended. Final score: 3-0",
          recorded_at: "2026-04-05T13:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 1,
      notes:
        "Easter Cup SF1 - Weatherhead cruise into the final with a dominant 3-0 win",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_SEMI_FINALS,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
