import type { Team } from "../../../core/entities/Team";
import { DEFAULT_TEAM_LOGO } from "../../../core/entities/Team";
import {
  generate_current_timestamp,
  SEED_GENDER_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_teams_men(
  lugogo_stadium_id: string,
  kyambogo_pitch_id: string,
  makerere_ground_id: string,
  entebbe_club_id: string,
  jinja_ground_id: string,
): import("$lib/core/types/DomainScalars").ScalarInput<Team>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      name: "Weatherhead Hockey Club",
      short_name: "WHC",
      description:
        "One of Uganda's oldest and most successful hockey clubs with a rich history",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.DENIS_ONYANGO,
      vice_captain_player_id: SEED_PLAYER_IDS.BRIAN_SSALI,
      max_squad_size: 18,
      home_venue_id: lugogo_stadium_id,
      primary_color: "#1E3A8A",
      secondary_color: "#FFFFFF",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://weatherheadhc.ug",
      founded_year: 1950,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.KAMPALA_HC,
      name: "Kampala Hockey Club",
      short_name: "KHC",
      description:
        "Premier hockey club based in Kampala with strong youth development program",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.RONALD_MUKIIBI,
      vice_captain_player_id: SEED_PLAYER_IDS.KAMPALA_P4,
      max_squad_size: 18,
      home_venue_id: lugogo_stadium_id,
      primary_color: "#DC2626",
      secondary_color: "#FBBF24",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://kampalahc.ug",
      founded_year: 1965,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.ROCKETS_HC,
      name: "Rockets Hockey Club",
      short_name: "RHC",
      description:
        "Dynamic and fast-paced hockey team known for attacking play",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.DANIEL_WASSWA,
      vice_captain_player_id: SEED_PLAYER_IDS.MOSES_ALOWO,
      max_squad_size: 18,
      home_venue_id: entebbe_club_id,
      primary_color: "#F59E0B",
      secondary_color: "#1F2937",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://rocketshc.ug",
      founded_year: 1980,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.WANANCHI_HC,
      name: "Wananchi Hockey Club",
      short_name: "WAN",
      description:
        "Community-focused hockey club with deep grassroots involvement",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.PETER_DRAGO,
      vice_captain_player_id: SEED_PLAYER_IDS.WANANCHI_P4,
      max_squad_size: 18,
      home_venue_id: jinja_ground_id,
      primary_color: "#16A34A",
      secondary_color: "#FFFFFF",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://wananchihc.ug",
      founded_year: 1975,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.MAKERERE_UNIVERSITY_HC,
      name: "Makerere University Hockey Club",
      short_name: "MAK",
      description:
        "University hockey club developing future national team stars",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.STEVEN_MUKASA,
      vice_captain_player_id: SEED_PLAYER_IDS.TIMOTHY_LUBEGA,
      max_squad_size: 18,
      home_venue_id: makerere_ground_id,
      primary_color: "#7C3AED",
      secondary_color: "#F3E8FF",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://makerere.ac.ug/hockey",
      founded_year: 1970,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.KYAMBOGO_UNIVERSITY_HC,
      name: "Kyambogo University Hockey Club",
      short_name: "KYU",
      description: "Rising university hockey team with talented young players",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.ISAAC_KATO,
      vice_captain_player_id: SEED_PLAYER_IDS.KYAMBOGO_P4,
      max_squad_size: 18,
      home_venue_id: kyambogo_pitch_id,
      primary_color: "#0891B2",
      secondary_color: "#ECFEFF",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://kyambogo.ac.ug/hockey",
      founded_year: 1990,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.SIMBA_HC,
      name: "Simba Hockey Club",
      short_name: "SIM",
      description: "Fierce competitors with strong defensive play style",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.FRANCIS_BYEKWASO,
      vice_captain_player_id: SEED_PLAYER_IDS.MICHAEL_OPIO,
      max_squad_size: 18,
      home_venue_id: lugogo_stadium_id,
      primary_color: "#EA580C",
      secondary_color: "#1F2937",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://simbahc.ug",
      founded_year: 1985,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.STRIKERS_HC,
      name: "Strikers Hockey Club",
      short_name: "STR",
      description: "Aggressive offensive team known for high-scoring matches",
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      gender_id: SEED_GENDER_IDS.MALE,
      captain_player_id: SEED_PLAYER_IDS.ROBERT_KIGGUNDU,
      vice_captain_player_id: SEED_PLAYER_IDS.STRIKERS_P4,
      max_squad_size: 18,
      home_venue_id: entebbe_club_id,
      primary_color: "#DB2777",
      secondary_color: "#FDF2F8",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://strikershc.ug",
      founded_year: 2000,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
