import type { GameEvent } from "../../../core/entities/Fixture";

export const GAME_EVENTS_EASTER_CUP_GROUP_B_1: import("$lib/core/types/DomainScalars").ScalarInput<GameEvent>[] = [
  {
    id: "game_event_g3_1",
    event_type: "period_start",
    minute: 0,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "First half started",
    recorded_at: "2025-03-28T14:00:00Z",
  },
  {
    id: "game_event_g3_2",
    event_type: "goal",
    minute: 5,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Daniel Wasswa",
    secondary_player_name: "",
    description: "Early goal by Daniel Wasswa - solo effort",
    recorded_at: "2025-03-28T14:05:00Z",
  },
  {
    id: "game_event_g3_3",
    event_type: "green_card",
    minute: 12,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "George Mugabi",
    secondary_player_name: "",
    description: "Green card warning to George Mugabi for delaying restart",
    recorded_at: "2025-03-28T14:12:00Z",
  },
  {
    id: "game_event_g3_4",
    event_type: "goal",
    minute: 18,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Judith Nakato",
    secondary_player_name: "Christine Amongi",
    description: "Goal by Judith Nakato assisted by Christine Amongi",
    recorded_at: "2025-03-28T14:18:00Z",
  },
  {
    id: "game_event_g3_5",
    event_type: "yellow_card",
    minute: 25,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "David Obua",
    secondary_player_name: "",
    description: "Yellow card to David Obua for persistent fouling",
    recorded_at: "2025-03-28T14:25:00Z",
  },
  {
    id: "game_event_g3_6",
    event_type: "goal",
    minute: 30,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Moses Alowo",
    secondary_player_name: "Carol Adoko",
    description: "Goal by Moses Alowo assisted by Carol Adoko",
    recorded_at: "2025-03-28T14:30:00Z",
  },
  {
    id: "game_event_g3_7",
    event_type: "period_end",
    minute: 35,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "First half ended. Score: 2-1",
    recorded_at: "2025-03-28T14:35:00Z",
  },
  {
    id: "game_event_g3_8",
    event_type: "period_start",
    minute: 35,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "Second half started",
    recorded_at: "2025-03-28T14:50:00Z",
  },
  {
    id: "game_event_g3_9",
    event_type: "substitution",
    minute: 40,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Betty Owori",
    secondary_player_name: "Patrick Ochieng",
    description: "Betty Owori replaced Patrick Ochieng",
    recorded_at: "2025-03-28T14:55:00Z",
  },
  {
    id: "game_event_g3_10",
    event_type: "second_yellow",
    minute: 48,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "David Obua",
    secondary_player_name: "",
    description: "Second yellow card to David Obua - sent off",
    recorded_at: "2025-03-28T15:03:00Z",
  },
  {
    id: "game_event_g3_11",
    event_type: "penalty_scored",
    minute: 52,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "George Mugabi",
    secondary_player_name: "",
    description: "Penalty corner goal by George Mugabi",
    recorded_at: "2025-03-28T15:07:00Z",
  },
  {
    id: "game_event_g3_12",
    event_type: "substitution",
    minute: 55,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Prossy Odongo",
    secondary_player_name: "Jennifer Achieng",
    description: "Prossy Odongo replaced Jennifer Achieng",
    recorded_at: "2025-03-28T15:10:00Z",
  },
  {
    id: "game_event_g3_13",
    event_type: "goal",
    minute: 60,
    stoppage_time_minute: null,
    team_side: "away",
    player_name: "Peter Drago",
    secondary_player_name: "Prossy Odongo",
    description: "Goal by Peter Drago assisted by Prossy Odongo",
    recorded_at: "2025-03-28T15:15:00Z",
  },
  {
    id: "game_event_g3_14",
    event_type: "substitution",
    minute: 63,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Winnie Akumu",
    secondary_player_name: "Edith Ogwal",
    description: "Winnie Akumu replaced Edith Ogwal",
    recorded_at: "2025-03-28T15:18:00Z",
  },
  {
    id: "game_event_g3_15",
    event_type: "goal",
    minute: 68,
    stoppage_time_minute: null,
    team_side: "home",
    player_name: "Carol Adoko",
    secondary_player_name: "Daniel Wasswa",
    description:
      "Goal by Carol Adoko assisted by Daniel Wasswa - seals the win",
    recorded_at: "2025-03-28T15:23:00Z",
  },
  {
    id: "game_event_g3_16",
    event_type: "period_end",
    minute: 70,
    stoppage_time_minute: null,
    team_side: "match",
    player_name: "",
    secondary_player_name: "",
    description: "Match ended. Final score: 4-2",
    recorded_at: "2025-03-28T15:25:00Z",
  },
];
