import type { Player } from "../../../core/entities/Player";
import type { ScalarValueInput } from "../../../core/types/DomainScalars";
import type { PositionIds } from "./seedPlayerIds";
import { SEED_PLAYER_IDS } from "./seedPlayerIds";

export function create_seed_players_group1(
  positions: PositionIds,
  organization_id: ScalarValueInput<Omit<Player, "gender_id">["organization_id"]>,
  now: Omit<Player, "gender_id">["created_at"],
): import("$lib/core/types/DomainScalars").ScalarInput<Omit<Player, "gender_id">>[] {
  return [
    {
      id: SEED_PLAYER_IDS.DENIS_ONYANGO,
      first_name: "Denis",
      last_name: "Onyango",
      email: "denis.onyango@weatherheadhc.ug",
      phone: "+256-700-100-001",
      date_of_birth: "1995-03-15",
      position_id: positions.gk,
      organization_id,
      height_cm: 175,
      weight_kg: 72,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Grace Onyango",
      emergency_contact_phone: "+256-700-100-101",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.BRIAN_SSALI,
      first_name: "Brian",
      last_name: "Ssali",
      email: "brian.ssali@weatherheadhc.ug",
      phone: "+256-700-100-002",
      date_of_birth: "1998-07-22",
      position_id: positions.sw,
      organization_id,
      height_cm: 178,
      weight_kg: 74,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Mary Ssali",
      emergency_contact_phone: "+256-700-100-102",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.JOSEPH_MUSOKE,
      first_name: "Joseph",
      last_name: "Musoke",
      email: "joseph.musoke@weatherheadhc.ug",
      phone: "+256-700-100-003",
      date_of_birth: "1997-11-08",
      position_id: positions.cb,
      organization_id,
      height_cm: 185,
      weight_kg: 80,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "John Musoke",
      emergency_contact_phone: "+256-700-100-103",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.RONALD_MUKIIBI,
      first_name: "Ronald",
      last_name: "Mukiibi",
      email: "ronald.mukiibi@kampalahc.ug",
      phone: "+256-700-200-001",
      date_of_birth: "1996-05-30",
      position_id: positions.gk,
      organization_id,
      height_cm: 180,
      weight_kg: 76,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Susan Mukiibi",
      emergency_contact_phone: "+256-700-200-101",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.SARAH_NAMUGWANYA,
      first_name: "Sarah",
      last_name: "Namugwanya",
      email: "sarah.namugwanya@kampalahc.ug",
      phone: "+256-700-200-002",
      date_of_birth: "1999-02-14",
      position_id: positions.sw,
      organization_id,
      height_cm: 168,
      weight_kg: 62,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Peter Namugwanya",
      emergency_contact_phone: "+256-700-200-102",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.PATRICIA_APOLOT,
      first_name: "Patricia",
      last_name: "Apolot",
      email: "patricia.apolot@kampalahc.ug",
      phone: "+256-700-200-003",
      date_of_birth: "2000-09-18",
      position_id: positions.cb,
      organization_id,
      height_cm: 165,
      weight_kg: 58,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "James Apolot",
      emergency_contact_phone: "+256-700-200-103",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.DANIEL_WASSWA,
      first_name: "Daniel",
      last_name: "Wasswa",
      email: "daniel.wasswa@rocketshc.ug",
      phone: "+256-700-300-001",
      date_of_birth: "1994-12-03",
      position_id: positions.gk,
      organization_id,
      height_cm: 182,
      weight_kg: 78,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Rose Wasswa",
      emergency_contact_phone: "+256-700-300-101",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.MOSES_ALOWO,
      first_name: "Moses",
      last_name: "Alowo",
      email: "moses.alowo@rocketshc.ug",
      phone: "+256-700-300-002",
      date_of_birth: "1998-04-25",
      position_id: positions.sw,
      organization_id,
      height_cm: 176,
      weight_kg: 73,
      nationality: "Uganda",
      profile_image_url: "",
      emergency_contact_name: "Helen Alowo",
      emergency_contact_phone: "+256-700-300-102",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}
