import type { Fixture } from "../../../core/entities/Fixture";
import {
  generate_current_timestamp,
  SEED_COMPETITION_IDS,
  SEED_FIXTURE_IDS,
  SEED_OFFICIAL_IDS,
  SEED_ORGANIZATION_IDS,
  SEED_STAGE_IDS,
  SEED_TEAM_IDS,
} from "./seedIds";

export function create_seed_fixtures_part12(
  referee_role_id: string,
  assistant_referee_role_id: string,
  next_week: Date,
  two_weeks: Date,
  three_weeks: Date,
): import("$lib/core/types/DomainScalars").ScalarInput<Fixture>[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_FIXTURE_IDS.EASTER_CUP_FINAL,
      organization_id: SEED_ORGANIZATION_IDS.UGANDA_HOCKEY_ASSOCIATION,
      competition_id: SEED_COMPETITION_IDS.EASTER_CUP_2026,
      round_number: 1,
      round_name: "Final",
      home_team_id: SEED_TEAM_IDS.WEATHERHEAD_HC,
      away_team_id: SEED_TEAM_IDS.ROCKETS_HC,
      venue: "Lugogo Hockey Stadium",
      scheduled_date: "2026-04-06",
      scheduled_time: "15:00",
      home_team_score: 1,
      away_team_score: 2,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: referee_role_id,
          role_name: "Umpire",
        },
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: assistant_referee_role_id,
          role_name: "Technical Table",
        },
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: assistant_referee_role_id,
          role_name: "Reserve Umpire",
        },
      ],
      game_events: [
        {
          id: "game_event_final_1",
          event_type: "period_start",
          minute: 0,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Final whistle - match underway",
          recorded_at: "2026-04-06T15:00:00Z",
        },
        {
          id: "game_event_final_2",
          event_type: "goal",
          minute: 14,
          stoppage_time_minute: 0,
          team_side: "away",
          player_name: "Daniel Wasswa",
          secondary_player_name: "Moses Alowo",
          description:
            "Rockets draw first blood - Daniel Wasswa finishes coolly",
          recorded_at: "2026-04-06T15:14:00Z",
        },
        {
          id: "game_event_final_3",
          event_type: "goal",
          minute: 27,
          stoppage_time_minute: 0,
          team_side: "home",
          player_name: "Denis Onyango",
          secondary_player_name: "Alex Kibuuka",
          description: "Weatherhead level - Denis Onyango drills home",
          recorded_at: "2026-04-06T15:27:00Z",
        },
        {
          id: "game_event_final_4",
          event_type: "period_end",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "First half ended. Score: 1-1",
          recorded_at: "2026-04-06T15:35:00Z",
        },
        {
          id: "game_event_final_5",
          event_type: "period_start",
          minute: 35,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "Second half started",
          recorded_at: "2026-04-06T15:50:00Z",
        },
        {
          id: "game_event_final_6",
          event_type: "goal",
          minute: 69,
          stoppage_time_minute: 0,
          team_side: "away",
          player_name: "George Mugabi",
          secondary_player_name: "Carol Adoko",
          description:
            "WINNER! George Mugabi breaks Weatherhead hearts with a late strike",
          recorded_at: "2026-04-06T16:24:00Z",
        },
        {
          id: "game_event_final_7",
          event_type: "period_end",
          minute: 70,
          stoppage_time_minute: 0,
          team_side: "match",
          player_name: "",
          secondary_player_name: "",
          description: "FULL TIME - Rockets HC are Easter Cup 2026 Champions!",
          recorded_at: "2026-04-06T16:25:00Z",
        },
      ],
      current_period: "finished",
      current_minute: 70,
      match_day: 1,
      notes:
        "Easter Cup 2026 Final - Rockets HC lift the trophy with a late George Mugabi winner",
      stage_id: SEED_STAGE_IDS.EASTER_CUP_FINAL,
      status: "completed",
      created_at: now,
      updated_at: now,
    },
  ];
}
