import type { CreateGameEventTypeInput } from "./GameEventTypeTypes";

export function get_play_and_control_event_types(
  organization_id: CreateGameEventTypeInput["organization_id"],
): CreateGameEventTypeInput[] {
  return [
    {
      name: "Substitution",
      code: "substitution",
      description: "A player substitution",
      icon: "🔄",
      color: "bg-blue-500 hover:bg-blue-600",
      category: "play",
      affects_score: false,
      requires_player: true,
      display_order: 9,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Foul",
      code: "foul",
      description: "A foul committed",
      icon: "⚠️",
      color: "bg-blue-500 hover:bg-blue-600",
      category: "play",
      affects_score: false,
      requires_player: true,
      display_order: 10,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Offside",
      code: "offside",
      description: "An offside infringement",
      icon: "🚫",
      color: "bg-purple-500 hover:bg-purple-600",
      category: "play",
      affects_score: false,
      requires_player: false,
      display_order: 11,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Corner Kick",
      code: "corner",
      description: "A corner kick awarded",
      icon: "🚩",
      color: "bg-teal-500 hover:bg-teal-600",
      category: "play",
      affects_score: false,
      requires_player: false,
      display_order: 12,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Penalty Corner",
      code: "penalty_corner",
      description: "A penalty corner awarded in field hockey",
      icon: "🏑",
      color: "bg-cyan-500 hover:bg-cyan-600",
      category: "play",
      affects_score: false,
      requires_player: false,
      display_order: 13,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Free Kick",
      code: "free_kick",
      description: "A free kick awarded",
      icon: "🦵",
      color: "bg-indigo-500 hover:bg-indigo-600",
      category: "play",
      affects_score: false,
      requires_player: false,
      display_order: 14,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Injury",
      code: "injury",
      description: "An injury stoppage",
      icon: "🏥",
      color: "bg-red-500 hover:bg-red-600",
      category: "play",
      affects_score: false,
      requires_player: true,
      display_order: 15,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "VAR Review",
      code: "var_review",
      description: "A video assistant referee review",
      icon: "📺",
      color: "bg-gray-600 hover:bg-gray-700",
      category: "match_control",
      affects_score: false,
      requires_player: false,
      display_order: 16,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Period Start",
      code: "period_start",
      description: "Start of a match period",
      icon: "▶️",
      color: "bg-emerald-500 hover:bg-emerald-600",
      category: "match_control",
      affects_score: false,
      requires_player: false,
      display_order: 17,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Period End",
      code: "period_end",
      description: "End of a match period",
      icon: "⏹️",
      color: "bg-slate-500 hover:bg-slate-600",
      category: "match_control",
      affects_score: false,
      requires_player: false,
      display_order: 18,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Short Corner",
      code: "short_corner",
      description: "A short corner (penalty corner) awarded in field hockey",
      icon: "🏑",
      color: "bg-orange-500 hover:bg-orange-600",
      category: "play",
      affects_score: false,
      requires_player: false,
      display_order: 19,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Penalty Stroke",
      code: "penalty_stroke",
      description: "A penalty stroke awarded in field hockey",
      icon: "🎯",
      color: "bg-violet-500 hover:bg-violet-600",
      category: "play",
      affects_score: false,
      requires_player: true,
      display_order: 20,
      sport_id: null,
      status: "active",
      organization_id,
    },
  ];
}
