import type { CreateGameEventTypeInput } from "./GameEventTypeTypes";

export function get_scoring_and_discipline_event_types(
  organization_id: CreateGameEventTypeInput["organization_id"],
): CreateGameEventTypeInput[] {
  return [
    {
      name: "Goal",
      code: "goal",
      description: "A goal scored by a player",
      icon: "⚽",
      color: "bg-green-500 hover:bg-green-600",
      category: "score",
      affects_score: true,
      requires_player: true,
      display_order: 1,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Own Goal",
      code: "own_goal",
      description: "A goal scored into one's own net",
      icon: "🥅",
      color: "bg-blue-500 hover:bg-blue-600",
      category: "score",
      affects_score: true,
      requires_player: true,
      display_order: 2,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Penalty Scored",
      code: "penalty_scored",
      description: "A penalty kick that resulted in a goal",
      icon: "🎯",
      color: "bg-green-600 hover:bg-green-700",
      category: "score",
      affects_score: true,
      requires_player: true,
      display_order: 3,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Penalty Missed",
      code: "penalty_missed",
      description: "A penalty kick that was missed or saved",
      icon: "❌",
      color: "bg-red-400 hover:bg-red-500",
      category: "score",
      affects_score: false,
      requires_player: true,
      display_order: 4,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Yellow Card",
      code: "yellow_card",
      description: "A caution shown to a player",
      icon: "🟨",
      color: "bg-yellow-400 hover:bg-yellow-500",
      category: "discipline",
      affects_score: false,
      requires_player: true,
      display_order: 5,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Red Card",
      code: "red_card",
      description: "A player sent off the field",
      icon: "🟥",
      color: "bg-red-600 hover:bg-red-700",
      category: "discipline",
      affects_score: false,
      requires_player: true,
      display_order: 6,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Second Yellow Card",
      code: "second_yellow",
      description: "A second caution resulting in a sending off",
      icon: "🟨🟥",
      color: "bg-blue-600 hover:bg-blue-700",
      category: "discipline",
      affects_score: false,
      requires_player: true,
      display_order: 7,
      sport_id: null,
      status: "active",
      organization_id,
    },
    {
      name: "Green Card",
      code: "green_card",
      description: "A warning card used in field hockey",
      icon: "🟩",
      color: "bg-green-400 hover:bg-green-500",
      category: "discipline",
      affects_score: false,
      requires_player: true,
      display_order: 8,
      sport_id: null,
      status: "active",
      organization_id,
    },
  ];
}
