import type { EntityMetadata } from "../../core/entities/BaseEntity";
import type { GameEventLog } from "../../core/entities/GameEventLog";
import {
  GAME_EVENT_TYPE_OPTIONS,
  TEAM_SIDE_OPTIONS,
} from "../../core/entities/GameEventLog";

export function register_game_event_log_metadata(
  metadata_map: Map<string, EntityMetadata>,
): Map<string, EntityMetadata> {
  metadata_map.set("gameeventlog", {
    entity_name: "gameeventlog",
    display_name: "Game Event Log",
    fields: [
      {
        field_name: "organization_id" satisfies keyof GameEventLog,
        display_name: "Organization",
        field_type: "foreign_key",
        foreign_key_entity: "organization",
        is_required: true,
        is_read_only: false,
        show_in_list: false,
      },
      {
        field_name: "live_game_log_id" satisfies keyof GameEventLog,
        display_name: "Live Game",
        field_type: "foreign_key",
        foreign_key_entity: "livegamelog",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
        foreign_key_filter: {
          depends_on_field: "organization_id",
          filter_type: "live_game_logs_from_organization",
        },
      },
      {
        field_name: "fixture_id" satisfies keyof GameEventLog,
        display_name: "Fixture",
        field_type: "foreign_key",
        foreign_key_entity: "fixture",
        is_required: true,
        is_read_only: false,
        show_in_list: false,
        foreign_key_filter: {
          depends_on_field: "organization_id",
          filter_type: "fixtures_from_organization",
        },
      },
      {
        field_name: "event_type" satisfies keyof GameEventLog,
        display_name: "Event Type",
        field_type: "enum",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
        enum_options: GAME_EVENT_TYPE_OPTIONS,
      },
      {
        field_name: "minute" satisfies keyof GameEventLog,
        display_name: "Minute",
        field_type: "number",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
      },
      {
        field_name: "stoppage_time_minute" satisfies keyof GameEventLog,
        display_name: "Stoppage Time Minute",
        field_type: "number",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
      },
      {
        field_name: "team_side" satisfies keyof GameEventLog,
        display_name: "Team Side",
        field_type: "enum",
        is_required: false,
        is_read_only: false,
        show_in_list: true,
        enum_options: TEAM_SIDE_OPTIONS,
      },
      {
        field_name: "player_id" satisfies keyof GameEventLog,
        display_name: "Player",
        field_type: "foreign_key",
        foreign_key_entity: "player",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
        foreign_key_filter: {
          depends_on_field: "organization_id",
          filter_type: "players_from_organization",
        },
      },
      {
        field_name: "player_name" satisfies keyof GameEventLog,
        display_name: "Player Name",
        field_type: "string",
        is_required: false,
        is_read_only: false,
        show_in_list: true,
      },
      {
        field_name: "secondary_player_id" satisfies keyof GameEventLog,
        display_name: "Secondary Player",
        field_type: "foreign_key",
        foreign_key_entity: "player",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
        foreign_key_filter: {
          depends_on_field: "organization_id",
          filter_type: "players_from_organization",
        },
      },
      {
        field_name: "secondary_player_name" satisfies keyof GameEventLog,
        display_name: "Secondary Player Name",
        field_type: "string",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
      },
      {
        field_name: "description" satisfies keyof GameEventLog,
        display_name: "Description",
        field_type: "string",
        is_required: false,
        is_read_only: false,
        show_in_list: true,
      },
      {
        field_name: "affects_score" satisfies keyof GameEventLog,
        display_name: "Affects Score",
        field_type: "boolean",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
      },
      {
        field_name: "voided" satisfies keyof GameEventLog,
        display_name: "Voided",
        field_type: "boolean",
        is_required: false,
        is_read_only: true,
        show_in_list: true,
      },
      {
        field_name: "voided_reason" satisfies keyof GameEventLog,
        display_name: "Voided Reason",
        field_type: "string",
        is_required: false,
        is_read_only: true,
        show_in_list: false,
      },
      {
        field_name: "status" satisfies keyof GameEventLog,
        display_name: "Status",
        field_type: "enum",
        is_required: true,
        is_read_only: false,
        enum_values: ["active", "inactive", "archived"],
        show_in_list: true,
      },
    ],
  });
  return metadata_map;
}
