import type { EntityMetadata } from "../../core/entities/BaseEntity";
import type { TeamStaff } from "../../core/entities/TeamStaff";
import { get_country_names_sorted_unique } from "../utils/countries";

export function register_team_staff_metadata(
  metadata_map: Map<string, EntityMetadata>,
): Map<string, EntityMetadata> {
  metadata_map.set("teamstaff", {
    entity_name: "teamstaff",
    display_name: "Team Staff",
    fields: [
      {
        field_name: "organization_id" satisfies keyof TeamStaff,
        display_name: "Organization",
        field_type: "foreign_key",
        foreign_key_entity: "organization",
        is_required: true,
        is_read_only: false,
        show_in_list: false,
      },
      {
        field_name: "first_name" satisfies keyof TeamStaff,
        display_name: "First Name",
        field_type: "string",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
      },
      {
        field_name: "last_name" satisfies keyof TeamStaff,
        display_name: "Last Name",
        field_type: "string",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
      },
      {
        field_name: "email" satisfies keyof TeamStaff,
        display_name: "Email",
        field_type: "string",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
      },
      {
        field_name: "phone" satisfies keyof TeamStaff,
        display_name: "Phone",
        field_type: "string",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "date_of_birth" satisfies keyof TeamStaff,
        display_name: "Date of Birth",
        field_type: "date",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "team_id" satisfies keyof TeamStaff,
        display_name: "Team",
        field_type: "foreign_key",
        foreign_key_entity: "team",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
        foreign_key_filter: {
          depends_on_field: "organization_id",
          filter_type: "teams_from_organization",
        },
      },
      {
        field_name: "role_id" satisfies keyof TeamStaff,
        display_name: "Staff Role",
        field_type: "foreign_key",
        foreign_key_entity: "teamstaffrole",
        is_required: true,
        is_read_only: false,
        show_in_list: true,
        foreign_key_filter: {
          depends_on_field: "organization_id",
          filter_type: "lookup_from_organization",
        },
      },
      {
        field_name: "nationality" satisfies keyof TeamStaff,
        display_name: "Nationality",
        field_type: "enum",
        is_required: false,
        is_read_only: false,
        enum_values: get_country_names_sorted_unique(),
      },
      {
        field_name: "profile_image_url" satisfies keyof TeamStaff,
        display_name: "Profile Image",
        field_type: "file",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "employment_start_date" satisfies keyof TeamStaff,
        display_name: "Employment Start Date",
        field_type: "date",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "employment_end_date" satisfies keyof TeamStaff,
        display_name: "Employment End Date",
        field_type: "date",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "emergency_contact_name" satisfies keyof TeamStaff,
        display_name: "Emergency Contact Name",
        field_type: "string",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "emergency_contact_phone" satisfies keyof TeamStaff,
        display_name: "Emergency Contact Phone",
        field_type: "string",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "notes" satisfies keyof TeamStaff,
        display_name: "Notes",
        field_type: "string",
        is_required: false,
        is_read_only: false,
      },
      {
        field_name: "status" satisfies keyof TeamStaff,
        display_name: "Status",
        field_type: "enum",
        enum_values: ["active", "inactive", "archived"],
        is_required: true,
        is_read_only: false,
        show_in_list: true,
      },
      {
        field_name: "qualifications",
        display_name: "Qualifications & Certifications",
        field_type: "sub_entity",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
        sub_entity_config: {
          child_entity_type: "qualification",
          foreign_key_field: "holder_id",
          holder_type_field: "holder_type",
          holder_type_value: "team_staff",
        },
      },
      {
        field_name: "identifications",
        display_name: "Identity Documents",
        field_type: "sub_entity",
        is_required: false,
        is_read_only: false,
        show_in_list: false,
        sub_entity_config: {
          child_entity_type: "identification",
          foreign_key_field: "holder_id",
          holder_type_field: "holder_type",
          holder_type_value: "team_staff",
        },
      },
    ],
  });
  return metadata_map;
}
